// Code generated by tools/wireconstants; DO NOT EDIT.

// Package generatedwire preserves the historical generated model import path.
package generatedwire

import "github.com/portpowered/go-tplink/pkg/dependencymodels"

// CloudErrorResponse is a compatibility alias for dependencymodels.CloudErrorResponse.
type CloudErrorResponse = dependencymodels.CloudErrorResponse

// CloudRequest is a compatibility alias for dependencymodels.CloudRequest.
type CloudRequest = dependencymodels.CloudRequest

// CloudResponse is a compatibility alias for dependencymodels.CloudResponse.
type CloudResponse = dependencymodels.CloudResponse

// CloudResponseEnvelope is a compatibility alias for dependencymodels.CloudResponseEnvelope.
type CloudResponseEnvelope = dependencymodels.CloudResponseEnvelope

// CommandAcknowledgement is a compatibility alias for dependencymodels.CommandAcknowledgement.
type CommandAcknowledgement = dependencymodels.CommandAcknowledgement

// Device is a compatibility alias for dependencymodels.Device.
type Device = dependencymodels.Device

// DeviceCommandError is a compatibility alias for dependencymodels.DeviceCommandError.
type DeviceCommandError = dependencymodels.DeviceCommandError

// DeviceListResponse is a compatibility alias for dependencymodels.DeviceListResponse.
type DeviceListResponse = dependencymodels.DeviceListResponse

// DeviceListResult is a compatibility alias for dependencymodels.DeviceListResult.
type DeviceListResult = dependencymodels.DeviceListResult

// GetDeviceListCloudRequest is a compatibility alias for dependencymodels.GetDeviceListCloudRequest.
type GetDeviceListCloudRequest = dependencymodels.GetDeviceListCloudRequest

// GetDeviceListCloudRequestMethod is a compatibility alias for dependencymodels.GetDeviceListCloudRequestMethod.
type GetDeviceListCloudRequestMethod = dependencymodels.GetDeviceListCloudRequestMethod

// LightState is a compatibility alias for dependencymodels.LightState.
type LightState = dependencymodels.LightState

// LightTransitionState is a compatibility alias for dependencymodels.LightTransitionState.
type LightTransitionState = dependencymodels.LightTransitionState

// LightTransitionStateOnOff is a compatibility alias for dependencymodels.LightTransitionStateOnOff.
type LightTransitionStateOnOff = dependencymodels.LightTransitionStateOnOff

// LightingCommandResult is a compatibility alias for dependencymodels.LightingCommandResult.
type LightingCommandResult = dependencymodels.LightingCommandResult

// LightingCommandResult_SmartlifeIotSmartbulbLightingservice is a compatibility alias for dependencymodels.LightingCommandResult_SmartlifeIotSmartbulbLightingservice.
type LightingCommandResult_SmartlifeIotSmartbulbLightingservice = dependencymodels.LightingCommandResult_SmartlifeIotSmartbulbLightingservice

// LightingGetLightStateCommand is a compatibility alias for dependencymodels.LightingGetLightStateCommand.
type LightingGetLightStateCommand = dependencymodels.LightingGetLightStateCommand

// LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState is a compatibility alias for dependencymodels.LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState.
type LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState = dependencymodels.LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState

// LightingTransitionLightStateCommand is a compatibility alias for dependencymodels.LightingTransitionLightStateCommand.
type LightingTransitionLightStateCommand = dependencymodels.LightingTransitionLightStateCommand

// LoginCloudRequest is a compatibility alias for dependencymodels.LoginCloudRequest.
type LoginCloudRequest = dependencymodels.LoginCloudRequest

// LoginCloudRequestMethod is a compatibility alias for dependencymodels.LoginCloudRequestMethod.
type LoginCloudRequestMethod = dependencymodels.LoginCloudRequestMethod

// LoginParams is a compatibility alias for dependencymodels.LoginParams.
type LoginParams = dependencymodels.LoginParams

// LoginParamsAppType is a compatibility alias for dependencymodels.LoginParamsAppType.
type LoginParamsAppType = dependencymodels.LoginParamsAppType

// LoginParamsTerminalUUID is a compatibility alias for dependencymodels.LoginParamsTerminalUUID.
type LoginParamsTerminalUUID = dependencymodels.LoginParamsTerminalUUID

// LoginResponse is a compatibility alias for dependencymodels.LoginResponse.
type LoginResponse = dependencymodels.LoginResponse

// LoginResult is a compatibility alias for dependencymodels.LoginResult.
type LoginResult = dependencymodels.LoginResult

// PassthroughCloudRequest is a compatibility alias for dependencymodels.PassthroughCloudRequest.
type PassthroughCloudRequest = dependencymodels.PassthroughCloudRequest

// PassthroughCloudRequestMethod is a compatibility alias for dependencymodels.PassthroughCloudRequestMethod.
type PassthroughCloudRequestMethod = dependencymodels.PassthroughCloudRequestMethod

// PassthroughCommand is a compatibility alias for dependencymodels.PassthroughCommand.
type PassthroughCommand = dependencymodels.PassthroughCommand

// PassthroughCommandResult is a compatibility alias for dependencymodels.PassthroughCommandResult.
type PassthroughCommandResult = dependencymodels.PassthroughCommandResult

// PassthroughParams is a compatibility alias for dependencymodels.PassthroughParams.
type PassthroughParams = dependencymodels.PassthroughParams

// PassthroughResponse is a compatibility alias for dependencymodels.PassthroughResponse.
type PassthroughResponse = dependencymodels.PassthroughResponse

// PassthroughResult is a compatibility alias for dependencymodels.PassthroughResult.
type PassthroughResult = dependencymodels.PassthroughResult

// SendCloudRequestJSONRequestBody is a compatibility alias for dependencymodels.SendCloudRequestJSONRequestBody.
type SendCloudRequestJSONRequestBody = dependencymodels.SendCloudRequestJSONRequestBody

// SendCloudRequestParams is a compatibility alias for dependencymodels.SendCloudRequestParams.
type SendCloudRequestParams = dependencymodels.SendCloudRequestParams

// SysInfo is a compatibility alias for dependencymodels.SysInfo.
type SysInfo = dependencymodels.SysInfo

// SystemCommandResult is a compatibility alias for dependencymodels.SystemCommandResult.
type SystemCommandResult = dependencymodels.SystemCommandResult

// SystemCommandResult_System is a compatibility alias for dependencymodels.SystemCommandResult_System.
type SystemCommandResult_System = dependencymodels.SystemCommandResult_System

// SystemGetSysInfoCommand is a compatibility alias for dependencymodels.SystemGetSysInfoCommand.
type SystemGetSysInfoCommand = dependencymodels.SystemGetSysInfoCommand

// SystemGetSysInfoCommandSystemGetSysinfo is a compatibility alias for dependencymodels.SystemGetSysInfoCommandSystemGetSysinfo.
type SystemGetSysInfoCommandSystemGetSysinfo = dependencymodels.SystemGetSysInfoCommandSystemGetSysinfo

// SystemRebootCommand is a compatibility alias for dependencymodels.SystemRebootCommand.
type SystemRebootCommand = dependencymodels.SystemRebootCommand

// SystemRebootCommandSystemRebootDelay is a compatibility alias for dependencymodels.SystemRebootCommandSystemRebootDelay.
type SystemRebootCommandSystemRebootDelay = dependencymodels.SystemRebootCommandSystemRebootDelay

// SystemSetDevAliasCommand is a compatibility alias for dependencymodels.SystemSetDevAliasCommand.
type SystemSetDevAliasCommand = dependencymodels.SystemSetDevAliasCommand

// SystemSetRelayStateCommand is a compatibility alias for dependencymodels.SystemSetRelayStateCommand.
type SystemSetRelayStateCommand = dependencymodels.SystemSetRelayStateCommand

// SystemSetRelayStateCommandSystemSetRelayStateState is a compatibility alias for dependencymodels.SystemSetRelayStateCommandSystemSetRelayStateState.
type SystemSetRelayStateCommandSystemSetRelayStateState = dependencymodels.SystemSetRelayStateCommandSystemSetRelayStateState

// GetDeviceList is a compatibility alias for dependencymodels.GetDeviceList.
const GetDeviceList = dependencymodels.GetDeviceList

// GoTplinkClient is a compatibility alias for dependencymodels.GoTplinkClient.
const GoTplinkClient = dependencymodels.GoTplinkClient

// LightTransitionStateOnOffN0 is a compatibility alias for dependencymodels.LightTransitionStateOnOffN0.
const LightTransitionStateOnOffN0 = dependencymodels.LightTransitionStateOnOffN0

// LightTransitionStateOnOffN1 is a compatibility alias for dependencymodels.LightTransitionStateOnOffN1.
const LightTransitionStateOnOffN1 = dependencymodels.LightTransitionStateOnOffN1

// LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightStateEmpty is a compatibility alias for dependencymodels.LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightStateEmpty.
const LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightStateEmpty = dependencymodels.LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightStateEmpty

// Login is a compatibility alias for dependencymodels.Login.
const Login = dependencymodels.Login

// Passthrough is a compatibility alias for dependencymodels.Passthrough.
const Passthrough = dependencymodels.Passthrough

// SystemGetSysInfoCommandSystemGetSysinfoEmpty is a compatibility alias for dependencymodels.SystemGetSysInfoCommandSystemGetSysinfoEmpty.
const SystemGetSysInfoCommandSystemGetSysinfoEmpty = dependencymodels.SystemGetSysInfoCommandSystemGetSysinfoEmpty

// SystemRebootCommandSystemRebootDelayN1 is a compatibility alias for dependencymodels.SystemRebootCommandSystemRebootDelayN1.
const SystemRebootCommandSystemRebootDelayN1 = dependencymodels.SystemRebootCommandSystemRebootDelayN1

// SystemSetRelayStateCommandSystemSetRelayStateStateN0 is a compatibility alias for dependencymodels.SystemSetRelayStateCommandSystemSetRelayStateStateN0.
const SystemSetRelayStateCommandSystemSetRelayStateStateN0 = dependencymodels.SystemSetRelayStateCommandSystemSetRelayStateStateN0

// SystemSetRelayStateCommandSystemSetRelayStateStateN1 is a compatibility alias for dependencymodels.SystemSetRelayStateCommandSystemSetRelayStateStateN1.
const SystemSetRelayStateCommandSystemSetRelayStateStateN1 = dependencymodels.SystemSetRelayStateCommandSystemSetRelayStateStateN1

// TapoAndroid is a compatibility alias for dependencymodels.TapoAndroid.
const TapoAndroid = dependencymodels.TapoAndroid
