// Package generatedwire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package generatedwire

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetDeviceListCloudRequestMethod.
const (
	GetDeviceList GetDeviceListCloudRequestMethod = "getDeviceList"
)

// Valid indicates whether the value is a known member of the GetDeviceListCloudRequestMethod enum.
func (e GetDeviceListCloudRequestMethod) Valid() bool {
	switch e {
	case GetDeviceList:
		return true
	default:
		return false
	}
}

// Defines values for LightTransitionStateOnOff.
const (
	LightTransitionStateOnOffN0 LightTransitionStateOnOff = 0
	LightTransitionStateOnOffN1 LightTransitionStateOnOff = 1
)

// Valid indicates whether the value is a known member of the LightTransitionStateOnOff enum.
func (e LightTransitionStateOnOff) Valid() bool {
	switch e {
	case LightTransitionStateOnOffN0:
		return true
	case LightTransitionStateOnOffN1:
		return true
	default:
		return false
	}
}

// Defines values for LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState.
const (
	LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightStateEmpty LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState = ""
)

// Valid indicates whether the value is a known member of the LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState enum.
func (e LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState) Valid() bool {
	switch e {
	case LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightStateEmpty:
		return true
	default:
		return false
	}
}

// Defines values for LoginCloudRequestMethod.
const (
	Login LoginCloudRequestMethod = "login"
)

// Valid indicates whether the value is a known member of the LoginCloudRequestMethod enum.
func (e LoginCloudRequestMethod) Valid() bool {
	switch e {
	case Login:
		return true
	default:
		return false
	}
}

// Defines values for LoginParamsAppType.
const (
	TapoAndroid LoginParamsAppType = "Tapo_Android"
)

// Valid indicates whether the value is a known member of the LoginParamsAppType enum.
func (e LoginParamsAppType) Valid() bool {
	switch e {
	case TapoAndroid:
		return true
	default:
		return false
	}
}

// Defines values for LoginParamsTerminalUUID.
const (
	GoTplinkClient LoginParamsTerminalUUID = "go-tplink-client"
)

// Valid indicates whether the value is a known member of the LoginParamsTerminalUUID enum.
func (e LoginParamsTerminalUUID) Valid() bool {
	switch e {
	case GoTplinkClient:
		return true
	default:
		return false
	}
}

// Defines values for PassthroughCloudRequestMethod.
const (
	Passthrough PassthroughCloudRequestMethod = "passthrough"
)

// Valid indicates whether the value is a known member of the PassthroughCloudRequestMethod enum.
func (e PassthroughCloudRequestMethod) Valid() bool {
	switch e {
	case Passthrough:
		return true
	default:
		return false
	}
}

// Defines values for SystemGetSysInfoCommandSystemGetSysinfo.
const (
	SystemGetSysInfoCommandSystemGetSysinfoEmpty SystemGetSysInfoCommandSystemGetSysinfo = ""
)

// Valid indicates whether the value is a known member of the SystemGetSysInfoCommandSystemGetSysinfo enum.
func (e SystemGetSysInfoCommandSystemGetSysinfo) Valid() bool {
	switch e {
	case SystemGetSysInfoCommandSystemGetSysinfoEmpty:
		return true
	default:
		return false
	}
}

// Defines values for SystemRebootCommandSystemRebootDelay.
const (
	SystemRebootCommandSystemRebootDelayN1 SystemRebootCommandSystemRebootDelay = 1
)

// Valid indicates whether the value is a known member of the SystemRebootCommandSystemRebootDelay enum.
func (e SystemRebootCommandSystemRebootDelay) Valid() bool {
	switch e {
	case SystemRebootCommandSystemRebootDelayN1:
		return true
	default:
		return false
	}
}

// Defines values for SystemSetRelayStateCommandSystemSetRelayStateState.
const (
	SystemSetRelayStateCommandSystemSetRelayStateStateN0 SystemSetRelayStateCommandSystemSetRelayStateState = 0
	SystemSetRelayStateCommandSystemSetRelayStateStateN1 SystemSetRelayStateCommandSystemSetRelayStateState = 1
)

// Valid indicates whether the value is a known member of the SystemSetRelayStateCommandSystemSetRelayStateState enum.
func (e SystemSetRelayStateCommandSystemSetRelayStateState) Valid() bool {
	switch e {
	case SystemSetRelayStateCommandSystemSetRelayStateStateN0:
		return true
	case SystemSetRelayStateCommandSystemSetRelayStateStateN1:
		return true
	default:
		return false
	}
}

// CloudErrorResponse defines model for CloudErrorResponse.
type CloudErrorResponse struct {
	// ErrorCode Non-zero cloud error code. The implementation maps several known codes and preserves other non-zero codes as generic errors.
	ErrorCode int `json:"error_code"`

	// Msg Optional cloud error message.
	Msg *string `json:"msg,omitempty"`
}

// CloudRequest Discriminated request envelope for the single POST endpoint.
type CloudRequest struct {
	union json.RawMessage
}

// CloudResponse defines model for CloudResponse.
type CloudResponse struct {
	// ErrorCode Zero indicates success. Known cloud failures include -20004 (rate limit), -20651 (expired token), -20104 (parameter error), and -20601 (authentication error). Other non-zero codes may occur.
	ErrorCode *int `json:"error_code,omitempty"`

	// Msg Optional cloud error message.
	Msg *string `json:"msg,omitempty"`
}

// CloudResponseEnvelope Expected result or cloud-error shape. Responses have no method discriminator, and response models are permissive because the client unmarshals into zero-valued Go fields; the request method identifies the expected result.
type CloudResponseEnvelope struct {
	union json.RawMessage
}

// CommandAcknowledgement defines model for CommandAcknowledgement.
type CommandAcknowledgement struct {
	// ErrCode Zero indicates success; -1 indicates an unsupported command in the implemented client.
	ErrCode              *int                   `json:"err_code,omitempty"`
	ErrMsg               *string                `json:"err_msg,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Device Cloud device record. The client retains records with unknown deviceType values, but its Go model does not retain fields outside those listed here.
type Device struct {
	// Alias Display name shown to the user.
	Alias        *string `json:"alias,omitempty"`
	AppServerUrl *string `json:"appServerUrl,omitempty"`
	Brightness   *int    `json:"brightness,omitempty"`
	DeviceHwVer  *string `json:"deviceHwVer,omitempty"`

	// DeviceId Pass this value as params.deviceId for passthrough commands.
	DeviceId     *string `json:"deviceId,omitempty"`
	DeviceMac    *string `json:"deviceMac,omitempty"`
	DeviceModel  *string `json:"deviceModel,omitempty"`
	DeviceRegion *string `json:"deviceRegion,omitempty"`

	// DeviceType The client classifies the known plug and bulb values below; other values remain valid and are classified as Other.
	DeviceType   *string `json:"deviceType,omitempty"`
	FwId         *string `json:"fwId,omitempty"`
	FwVer        *string `json:"fwVer,omitempty"`
	HwId         *string `json:"hwId,omitempty"`
	IsSameRegion *bool   `json:"isSameRegion,omitempty"`

	// IsColor Cloud-reported capability flag; 1 indicates color support.
	IsColor *int `json:"is_color,omitempty"`

	// IsDimmable Cloud-reported capability flag; 1 indicates dimming support.
	IsDimmable *int `json:"is_dimmable,omitempty"`

	// IsVariableColorTemp Cloud-reported capability flag; 1 indicates color temperature support.
	IsVariableColorTemp *int    `json:"is_variable_color_temp,omitempty"`
	OemId               *string `json:"oemId,omitempty"`

	// Status Cloud-reported status; interpretation may vary by device.
	Status               *int                   `json:"status,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceCommandError defines model for DeviceCommandError.
type DeviceCommandError struct {
	// ErrCode Non-zero device-level error code; -1 indicates an unsupported command.
	ErrCode              int                    `json:"err_code"`
	ErrMsg               *string                `json:"err_msg,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceListResponse defines model for DeviceListResponse.
type DeviceListResponse struct {
	// ErrorCode Zero indicates success. Known cloud failures include -20004 (rate limit), -20651 (expired token), -20104 (parameter error), and -20601 (authentication error). Other non-zero codes may occur.
	ErrorCode *int `json:"error_code,omitempty"`

	// Msg Optional cloud error message.
	Msg *string `json:"msg,omitempty"`

	// Result The array may be empty. Each element is a cloud device record.
	Result *DeviceListResult `json:"result,omitempty"`
}

// DeviceListResult The array may be empty. Each element is a cloud device record.
type DeviceListResult struct {
	DeviceList *[]Device `json:"deviceList,omitempty"`
}

// GetDeviceListCloudRequest The implemented client sends no params for this method.
type GetDeviceListCloudRequest struct {
	Method GetDeviceListCloudRequestMethod `json:"method"`
}

// GetDeviceListCloudRequestMethod defines model for GetDeviceListCloudRequest.Method.
type GetDeviceListCloudRequestMethod string

// LightState defines model for LightState.
type LightState struct {
	Brightness           *int                   `json:"brightness,omitempty"`
	ColorTemp            *int                   `json:"color_temp,omitempty"`
	ErrCode              *int                   `json:"err_code,omitempty"`
	Hue                  *int                   `json:"hue,omitempty"`
	Mode                 *string                `json:"mode,omitempty"`
	OnOff                *int                   `json:"on_off,omitempty"`
	Saturation           *int                   `json:"saturation,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LightTransitionState State values accepted by SetLightState. Other properties may be sent by the generic method; device support depends on its capabilities.
type LightTransitionState struct {
	// Brightness Brightness from 0 through 100.
	Brightness *int `json:"brightness,omitempty"`

	// ColorTemp Color temperature in Kelvin; supported values depend on the device.
	ColorTemp *int `json:"color_temp,omitempty"`

	// Hue Hue from 0 through 360 degrees.
	Hue *int `json:"hue,omitempty"`

	// OnOff 1 turns the bulb on; 0 turns it off.
	OnOff *LightTransitionStateOnOff `json:"on_off,omitempty"`

	// Saturation Saturation from 0 through 100.
	Saturation           *int                   `json:"saturation,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LightTransitionStateOnOff 1 turns the bulb on; 0 turns it off.
type LightTransitionStateOnOff int

// LightingCommandResult defines model for LightingCommandResult.
type LightingCommandResult struct {
	SmartlifeIotSmartbulbLightingservice *LightingCommandResult_SmartlifeIotSmartbulbLightingservice `json:"smartlife.iot.smartbulb.lightingservice,omitempty"`
	AdditionalProperties                 map[string]interface{}                                      `json:"-"`
}

// LightingCommandResult_SmartlifeIotSmartbulbLightingservice defines model for LightingCommandResult.SmartlifeIotSmartbulbLightingservice.
type LightingCommandResult_SmartlifeIotSmartbulbLightingservice struct {
	GetLightState        *LightState             `json:"get_light_state,omitempty"`
	TransitionLightState *CommandAcknowledgement `json:"transition_light_state,omitempty"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// LightingGetLightStateCommand defines model for LightingGetLightStateCommand.
type LightingGetLightStateCommand struct {
	SmartlifeIotSmartbulbLightingservice struct {
		// GetLightState Empty string for the read command.
		GetLightState LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState `json:"get_light_state"`
	} `json:"smartlife.iot.smartbulb.lightingservice"`
}

// LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState Empty string for the read command.
type LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState string

// LightingTransitionLightStateCommand defines model for LightingTransitionLightStateCommand.
type LightingTransitionLightStateCommand struct {
	SmartlifeIotSmartbulbLightingservice struct {
		// TransitionLightState State values accepted by SetLightState. Other properties may be sent by the generic method; device support depends on its capabilities.
		TransitionLightState LightTransitionState `json:"transition_light_state"`
	} `json:"smartlife.iot.smartbulb.lightingservice"`
}

// LoginCloudRequest defines model for LoginCloudRequest.
type LoginCloudRequest struct {
	Method LoginCloudRequestMethod `json:"method"`
	Params LoginParams             `json:"params"`
}

// LoginCloudRequestMethod defines model for LoginCloudRequest.Method.
type LoginCloudRequestMethod string

// LoginParams defines model for LoginParams.
type LoginParams struct {
	// AppType Fixed appType value sent by this client.
	AppType LoginParamsAppType `json:"appType"`

	// CloudPassword Account password supplied to Login.
	CloudPassword *string `json:"cloudPassword,omitempty"`

	// CloudUserName Account email supplied to Login.
	CloudUserName string `json:"cloudUserName"`

	// TerminalUUID Fixed terminalUUID value sent by this client.
	TerminalUUID LoginParamsTerminalUUID `json:"terminalUUID"`
}

// LoginParamsAppType Fixed appType value sent by this client.
type LoginParamsAppType string

// LoginParamsTerminalUUID Fixed terminalUUID value sent by this client.
type LoginParamsTerminalUUID string

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// ErrorCode Zero indicates success. Known cloud failures include -20004 (rate limit), -20651 (expired token), -20104 (parameter error), and -20601 (authentication error). Other non-zero codes may occur.
	ErrorCode *int `json:"error_code,omitempty"`

	// Msg Optional cloud error message.
	Msg    *string      `json:"msg,omitempty"`
	Result *LoginResult `json:"result,omitempty"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	AccountId   *string `json:"accountId,omitempty"`
	CountryCode *string `json:"countryCode,omitempty"`
	Email       *string `json:"email,omitempty"`
	RegTime     *string `json:"regTime,omitempty"`

	// Token Opaque session token for subsequent authenticated requests.
	Token *string `json:"token,omitempty"`
}

// PassthroughCloudRequest defines model for PassthroughCloudRequest.
type PassthroughCloudRequest struct {
	Method PassthroughCloudRequestMethod `json:"method"`
	Params PassthroughParams             `json:"params"`
}

// PassthroughCloudRequestMethod defines model for PassthroughCloudRequest.Method.
type PassthroughCloudRequestMethod string

// PassthroughCommand Inner JSON value after decoding params.requestData. The client sends one command under one namespace per request.
type PassthroughCommand struct {
	union json.RawMessage
}

// PassthroughCommandResult Inner JSON value after decoding result.responseData.
type PassthroughCommandResult struct {
	union json.RawMessage
}

// PassthroughParams defines model for PassthroughParams.
type PassthroughParams struct {
	// DeviceId Device identifier from the device-list result.
	DeviceId string `json:"deviceId"`

	// RequestData JSON-encoded string containing one command object. Decode the string
	// to see the PassthroughCommand schema; do not send that object in
	// place of the string. The Guides list the fields for each command.
	RequestData string `json:"requestData"`
}

// PassthroughResponse defines model for PassthroughResponse.
type PassthroughResponse struct {
	// ErrorCode Zero indicates success. Known cloud failures include -20004 (rate limit), -20651 (expired token), -20104 (parameter error), and -20601 (authentication error). Other non-zero codes may occur.
	ErrorCode *int `json:"error_code,omitempty"`

	// Msg Optional cloud error message.
	Msg    *string            `json:"msg,omitempty"`
	Result *PassthroughResult `json:"result,omitempty"`
}

// PassthroughResult defines model for PassthroughResult.
type PassthroughResult struct {
	// ResponseData JSON-encoded device response. Decode the string to interpret
	// PassthroughCommandResult. Device errors may also appear at the top level.
	ResponseData *string `json:"responseData,omitempty"`
}

// SysInfo defines model for SysInfo.
type SysInfo struct {
	Alias                *string                `json:"alias,omitempty"`
	DeviceId             *string                `json:"deviceId,omitempty"`
	ErrCode              *int                   `json:"err_code,omitempty"`
	HwVer                *string                `json:"hw_ver,omitempty"`
	Model                *string                `json:"model,omitempty"`
	OnTime               *int                   `json:"on_time,omitempty"`
	RelayState           *int                   `json:"relay_state,omitempty"`
	SwVer                *string                `json:"sw_ver,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SystemCommandResult defines model for SystemCommandResult.
type SystemCommandResult struct {
	System               *SystemCommandResult_System `json:"system,omitempty"`
	AdditionalProperties map[string]interface{}      `json:"-"`
}

// SystemCommandResult_System defines model for SystemCommandResult.System.
type SystemCommandResult_System struct {
	GetSysinfo           *SysInfo                `json:"get_sysinfo,omitempty"`
	Reboot               *CommandAcknowledgement `json:"reboot,omitempty"`
	SetDevAlias          *CommandAcknowledgement `json:"set_dev_alias,omitempty"`
	SetRelayState        *CommandAcknowledgement `json:"set_relay_state,omitempty"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// SystemGetSysInfoCommand defines model for SystemGetSysInfoCommand.
type SystemGetSysInfoCommand struct {
	System struct {
		// GetSysinfo Empty string for the read command.
		GetSysinfo SystemGetSysInfoCommandSystemGetSysinfo `json:"get_sysinfo"`
	} `json:"system"`
}

// SystemGetSysInfoCommandSystemGetSysinfo Empty string for the read command.
type SystemGetSysInfoCommandSystemGetSysinfo string

// SystemRebootCommand defines model for SystemRebootCommand.
type SystemRebootCommand struct {
	System struct {
		Reboot struct {
			// Delay The implemented client sends a one-second delay.
			Delay SystemRebootCommandSystemRebootDelay `json:"delay"`
		} `json:"reboot"`
	} `json:"system"`
}

// SystemRebootCommandSystemRebootDelay The implemented client sends a one-second delay.
type SystemRebootCommandSystemRebootDelay int

// SystemSetDevAliasCommand defines model for SystemSetDevAliasCommand.
type SystemSetDevAliasCommand struct {
	System struct {
		SetDevAlias struct {
			Alias string `json:"alias"`
		} `json:"set_dev_alias"`
	} `json:"system"`
}

// SystemSetRelayStateCommand defines model for SystemSetRelayStateCommand.
type SystemSetRelayStateCommand struct {
	System struct {
		SetRelayState struct {
			// State 1 turns the relay on; 0 turns it off.
			State SystemSetRelayStateCommandSystemSetRelayStateState `json:"state"`
		} `json:"set_relay_state"`
	} `json:"system"`
}

// SystemSetRelayStateCommandSystemSetRelayStateState 1 turns the relay on; 0 turns it off.
type SystemSetRelayStateCommandSystemSetRelayStateState int

// SendCloudRequestParams defines parameters for SendCloudRequest.
type SendCloudRequestParams struct {
	// Token Session token. Omit for login. Required by the implemented client for getDeviceList and passthrough requests.
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// SendCloudRequestJSONRequestBody defines body for SendCloudRequest for application/json ContentType.
type SendCloudRequestJSONRequestBody = CloudRequest

// Getter for additional properties for CommandAcknowledgement. Returns the specified
// element and whether it was found
func (a CommandAcknowledgement) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CommandAcknowledgement
func (a *CommandAcknowledgement) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CommandAcknowledgement to handle AdditionalProperties
func (a *CommandAcknowledgement) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["err_code"]; found {
		err = json.Unmarshal(raw, &a.ErrCode)
		if err != nil {
			return fmt.Errorf("error reading 'err_code': %w", err)
		}
		delete(object, "err_code")
	}

	if raw, found := object["err_msg"]; found {
		err = json.Unmarshal(raw, &a.ErrMsg)
		if err != nil {
			return fmt.Errorf("error reading 'err_msg': %w", err)
		}
		delete(object, "err_msg")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CommandAcknowledgement to handle AdditionalProperties
func (a CommandAcknowledgement) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ErrCode != nil {
		object["err_code"], err = json.Marshal(a.ErrCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_code': %w", err)
		}
	}

	if a.ErrMsg != nil {
		object["err_msg"], err = json.Marshal(a.ErrMsg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_msg': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Device. Returns the specified
// element and whether it was found
func (a Device) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Device
func (a *Device) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a *Device) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["alias"]; found {
		err = json.Unmarshal(raw, &a.Alias)
		if err != nil {
			return fmt.Errorf("error reading 'alias': %w", err)
		}
		delete(object, "alias")
	}

	if raw, found := object["appServerUrl"]; found {
		err = json.Unmarshal(raw, &a.AppServerUrl)
		if err != nil {
			return fmt.Errorf("error reading 'appServerUrl': %w", err)
		}
		delete(object, "appServerUrl")
	}

	if raw, found := object["brightness"]; found {
		err = json.Unmarshal(raw, &a.Brightness)
		if err != nil {
			return fmt.Errorf("error reading 'brightness': %w", err)
		}
		delete(object, "brightness")
	}

	if raw, found := object["deviceHwVer"]; found {
		err = json.Unmarshal(raw, &a.DeviceHwVer)
		if err != nil {
			return fmt.Errorf("error reading 'deviceHwVer': %w", err)
		}
		delete(object, "deviceHwVer")
	}

	if raw, found := object["deviceId"]; found {
		err = json.Unmarshal(raw, &a.DeviceId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceId': %w", err)
		}
		delete(object, "deviceId")
	}

	if raw, found := object["deviceMac"]; found {
		err = json.Unmarshal(raw, &a.DeviceMac)
		if err != nil {
			return fmt.Errorf("error reading 'deviceMac': %w", err)
		}
		delete(object, "deviceMac")
	}

	if raw, found := object["deviceModel"]; found {
		err = json.Unmarshal(raw, &a.DeviceModel)
		if err != nil {
			return fmt.Errorf("error reading 'deviceModel': %w", err)
		}
		delete(object, "deviceModel")
	}

	if raw, found := object["deviceRegion"]; found {
		err = json.Unmarshal(raw, &a.DeviceRegion)
		if err != nil {
			return fmt.Errorf("error reading 'deviceRegion': %w", err)
		}
		delete(object, "deviceRegion")
	}

	if raw, found := object["deviceType"]; found {
		err = json.Unmarshal(raw, &a.DeviceType)
		if err != nil {
			return fmt.Errorf("error reading 'deviceType': %w", err)
		}
		delete(object, "deviceType")
	}

	if raw, found := object["fwId"]; found {
		err = json.Unmarshal(raw, &a.FwId)
		if err != nil {
			return fmt.Errorf("error reading 'fwId': %w", err)
		}
		delete(object, "fwId")
	}

	if raw, found := object["fwVer"]; found {
		err = json.Unmarshal(raw, &a.FwVer)
		if err != nil {
			return fmt.Errorf("error reading 'fwVer': %w", err)
		}
		delete(object, "fwVer")
	}

	if raw, found := object["hwId"]; found {
		err = json.Unmarshal(raw, &a.HwId)
		if err != nil {
			return fmt.Errorf("error reading 'hwId': %w", err)
		}
		delete(object, "hwId")
	}

	if raw, found := object["isSameRegion"]; found {
		err = json.Unmarshal(raw, &a.IsSameRegion)
		if err != nil {
			return fmt.Errorf("error reading 'isSameRegion': %w", err)
		}
		delete(object, "isSameRegion")
	}

	if raw, found := object["is_color"]; found {
		err = json.Unmarshal(raw, &a.IsColor)
		if err != nil {
			return fmt.Errorf("error reading 'is_color': %w", err)
		}
		delete(object, "is_color")
	}

	if raw, found := object["is_dimmable"]; found {
		err = json.Unmarshal(raw, &a.IsDimmable)
		if err != nil {
			return fmt.Errorf("error reading 'is_dimmable': %w", err)
		}
		delete(object, "is_dimmable")
	}

	if raw, found := object["is_variable_color_temp"]; found {
		err = json.Unmarshal(raw, &a.IsVariableColorTemp)
		if err != nil {
			return fmt.Errorf("error reading 'is_variable_color_temp': %w", err)
		}
		delete(object, "is_variable_color_temp")
	}

	if raw, found := object["oemId"]; found {
		err = json.Unmarshal(raw, &a.OemId)
		if err != nil {
			return fmt.Errorf("error reading 'oemId': %w", err)
		}
		delete(object, "oemId")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a Device) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Alias != nil {
		object["alias"], err = json.Marshal(a.Alias)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'alias': %w", err)
		}
	}

	if a.AppServerUrl != nil {
		object["appServerUrl"], err = json.Marshal(a.AppServerUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'appServerUrl': %w", err)
		}
	}

	if a.Brightness != nil {
		object["brightness"], err = json.Marshal(a.Brightness)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'brightness': %w", err)
		}
	}

	if a.DeviceHwVer != nil {
		object["deviceHwVer"], err = json.Marshal(a.DeviceHwVer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceHwVer': %w", err)
		}
	}

	if a.DeviceId != nil {
		object["deviceId"], err = json.Marshal(a.DeviceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceId': %w", err)
		}
	}

	if a.DeviceMac != nil {
		object["deviceMac"], err = json.Marshal(a.DeviceMac)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceMac': %w", err)
		}
	}

	if a.DeviceModel != nil {
		object["deviceModel"], err = json.Marshal(a.DeviceModel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceModel': %w", err)
		}
	}

	if a.DeviceRegion != nil {
		object["deviceRegion"], err = json.Marshal(a.DeviceRegion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceRegion': %w", err)
		}
	}

	if a.DeviceType != nil {
		object["deviceType"], err = json.Marshal(a.DeviceType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceType': %w", err)
		}
	}

	if a.FwId != nil {
		object["fwId"], err = json.Marshal(a.FwId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fwId': %w", err)
		}
	}

	if a.FwVer != nil {
		object["fwVer"], err = json.Marshal(a.FwVer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fwVer': %w", err)
		}
	}

	if a.HwId != nil {
		object["hwId"], err = json.Marshal(a.HwId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hwId': %w", err)
		}
	}

	if a.IsSameRegion != nil {
		object["isSameRegion"], err = json.Marshal(a.IsSameRegion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isSameRegion': %w", err)
		}
	}

	if a.IsColor != nil {
		object["is_color"], err = json.Marshal(a.IsColor)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_color': %w", err)
		}
	}

	if a.IsDimmable != nil {
		object["is_dimmable"], err = json.Marshal(a.IsDimmable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_dimmable': %w", err)
		}
	}

	if a.IsVariableColorTemp != nil {
		object["is_variable_color_temp"], err = json.Marshal(a.IsVariableColorTemp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_variable_color_temp': %w", err)
		}
	}

	if a.OemId != nil {
		object["oemId"], err = json.Marshal(a.OemId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'oemId': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DeviceCommandError. Returns the specified
// element and whether it was found
func (a DeviceCommandError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceCommandError
func (a *DeviceCommandError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceCommandError to handle AdditionalProperties
func (a *DeviceCommandError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["err_code"]; found {
		err = json.Unmarshal(raw, &a.ErrCode)
		if err != nil {
			return fmt.Errorf("error reading 'err_code': %w", err)
		}
		delete(object, "err_code")
	}

	if raw, found := object["err_msg"]; found {
		err = json.Unmarshal(raw, &a.ErrMsg)
		if err != nil {
			return fmt.Errorf("error reading 'err_msg': %w", err)
		}
		delete(object, "err_msg")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceCommandError to handle AdditionalProperties
func (a DeviceCommandError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["err_code"], err = json.Marshal(a.ErrCode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'err_code': %w", err)
	}

	if a.ErrMsg != nil {
		object["err_msg"], err = json.Marshal(a.ErrMsg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_msg': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LightState. Returns the specified
// element and whether it was found
func (a LightState) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LightState
func (a *LightState) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LightState to handle AdditionalProperties
func (a *LightState) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["brightness"]; found {
		err = json.Unmarshal(raw, &a.Brightness)
		if err != nil {
			return fmt.Errorf("error reading 'brightness': %w", err)
		}
		delete(object, "brightness")
	}

	if raw, found := object["color_temp"]; found {
		err = json.Unmarshal(raw, &a.ColorTemp)
		if err != nil {
			return fmt.Errorf("error reading 'color_temp': %w", err)
		}
		delete(object, "color_temp")
	}

	if raw, found := object["err_code"]; found {
		err = json.Unmarshal(raw, &a.ErrCode)
		if err != nil {
			return fmt.Errorf("error reading 'err_code': %w", err)
		}
		delete(object, "err_code")
	}

	if raw, found := object["hue"]; found {
		err = json.Unmarshal(raw, &a.Hue)
		if err != nil {
			return fmt.Errorf("error reading 'hue': %w", err)
		}
		delete(object, "hue")
	}

	if raw, found := object["mode"]; found {
		err = json.Unmarshal(raw, &a.Mode)
		if err != nil {
			return fmt.Errorf("error reading 'mode': %w", err)
		}
		delete(object, "mode")
	}

	if raw, found := object["on_off"]; found {
		err = json.Unmarshal(raw, &a.OnOff)
		if err != nil {
			return fmt.Errorf("error reading 'on_off': %w", err)
		}
		delete(object, "on_off")
	}

	if raw, found := object["saturation"]; found {
		err = json.Unmarshal(raw, &a.Saturation)
		if err != nil {
			return fmt.Errorf("error reading 'saturation': %w", err)
		}
		delete(object, "saturation")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LightState to handle AdditionalProperties
func (a LightState) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Brightness != nil {
		object["brightness"], err = json.Marshal(a.Brightness)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'brightness': %w", err)
		}
	}

	if a.ColorTemp != nil {
		object["color_temp"], err = json.Marshal(a.ColorTemp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'color_temp': %w", err)
		}
	}

	if a.ErrCode != nil {
		object["err_code"], err = json.Marshal(a.ErrCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_code': %w", err)
		}
	}

	if a.Hue != nil {
		object["hue"], err = json.Marshal(a.Hue)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hue': %w", err)
		}
	}

	if a.Mode != nil {
		object["mode"], err = json.Marshal(a.Mode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mode': %w", err)
		}
	}

	if a.OnOff != nil {
		object["on_off"], err = json.Marshal(a.OnOff)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'on_off': %w", err)
		}
	}

	if a.Saturation != nil {
		object["saturation"], err = json.Marshal(a.Saturation)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'saturation': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LightTransitionState. Returns the specified
// element and whether it was found
func (a LightTransitionState) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LightTransitionState
func (a *LightTransitionState) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LightTransitionState to handle AdditionalProperties
func (a *LightTransitionState) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["brightness"]; found {
		err = json.Unmarshal(raw, &a.Brightness)
		if err != nil {
			return fmt.Errorf("error reading 'brightness': %w", err)
		}
		delete(object, "brightness")
	}

	if raw, found := object["color_temp"]; found {
		err = json.Unmarshal(raw, &a.ColorTemp)
		if err != nil {
			return fmt.Errorf("error reading 'color_temp': %w", err)
		}
		delete(object, "color_temp")
	}

	if raw, found := object["hue"]; found {
		err = json.Unmarshal(raw, &a.Hue)
		if err != nil {
			return fmt.Errorf("error reading 'hue': %w", err)
		}
		delete(object, "hue")
	}

	if raw, found := object["on_off"]; found {
		err = json.Unmarshal(raw, &a.OnOff)
		if err != nil {
			return fmt.Errorf("error reading 'on_off': %w", err)
		}
		delete(object, "on_off")
	}

	if raw, found := object["saturation"]; found {
		err = json.Unmarshal(raw, &a.Saturation)
		if err != nil {
			return fmt.Errorf("error reading 'saturation': %w", err)
		}
		delete(object, "saturation")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LightTransitionState to handle AdditionalProperties
func (a LightTransitionState) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Brightness != nil {
		object["brightness"], err = json.Marshal(a.Brightness)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'brightness': %w", err)
		}
	}

	if a.ColorTemp != nil {
		object["color_temp"], err = json.Marshal(a.ColorTemp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'color_temp': %w", err)
		}
	}

	if a.Hue != nil {
		object["hue"], err = json.Marshal(a.Hue)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hue': %w", err)
		}
	}

	if a.OnOff != nil {
		object["on_off"], err = json.Marshal(a.OnOff)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'on_off': %w", err)
		}
	}

	if a.Saturation != nil {
		object["saturation"], err = json.Marshal(a.Saturation)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'saturation': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LightingCommandResult. Returns the specified
// element and whether it was found
func (a LightingCommandResult) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LightingCommandResult
func (a *LightingCommandResult) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LightingCommandResult to handle AdditionalProperties
func (a *LightingCommandResult) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["smartlife.iot.smartbulb.lightingservice"]; found {
		err = json.Unmarshal(raw, &a.SmartlifeIotSmartbulbLightingservice)
		if err != nil {
			return fmt.Errorf("error reading 'smartlife.iot.smartbulb.lightingservice': %w", err)
		}
		delete(object, "smartlife.iot.smartbulb.lightingservice")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LightingCommandResult to handle AdditionalProperties
func (a LightingCommandResult) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.SmartlifeIotSmartbulbLightingservice != nil {
		object["smartlife.iot.smartbulb.lightingservice"], err = json.Marshal(a.SmartlifeIotSmartbulbLightingservice)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'smartlife.iot.smartbulb.lightingservice': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LightingCommandResult_SmartlifeIotSmartbulbLightingservice. Returns the specified
// element and whether it was found
func (a LightingCommandResult_SmartlifeIotSmartbulbLightingservice) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LightingCommandResult_SmartlifeIotSmartbulbLightingservice
func (a *LightingCommandResult_SmartlifeIotSmartbulbLightingservice) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LightingCommandResult_SmartlifeIotSmartbulbLightingservice to handle AdditionalProperties
func (a *LightingCommandResult_SmartlifeIotSmartbulbLightingservice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["get_light_state"]; found {
		err = json.Unmarshal(raw, &a.GetLightState)
		if err != nil {
			return fmt.Errorf("error reading 'get_light_state': %w", err)
		}
		delete(object, "get_light_state")
	}

	if raw, found := object["transition_light_state"]; found {
		err = json.Unmarshal(raw, &a.TransitionLightState)
		if err != nil {
			return fmt.Errorf("error reading 'transition_light_state': %w", err)
		}
		delete(object, "transition_light_state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LightingCommandResult_SmartlifeIotSmartbulbLightingservice to handle AdditionalProperties
func (a LightingCommandResult_SmartlifeIotSmartbulbLightingservice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.GetLightState != nil {
		object["get_light_state"], err = json.Marshal(a.GetLightState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'get_light_state': %w", err)
		}
	}

	if a.TransitionLightState != nil {
		object["transition_light_state"], err = json.Marshal(a.TransitionLightState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'transition_light_state': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SysInfo. Returns the specified
// element and whether it was found
func (a SysInfo) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SysInfo
func (a *SysInfo) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SysInfo to handle AdditionalProperties
func (a *SysInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["alias"]; found {
		err = json.Unmarshal(raw, &a.Alias)
		if err != nil {
			return fmt.Errorf("error reading 'alias': %w", err)
		}
		delete(object, "alias")
	}

	if raw, found := object["deviceId"]; found {
		err = json.Unmarshal(raw, &a.DeviceId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceId': %w", err)
		}
		delete(object, "deviceId")
	}

	if raw, found := object["err_code"]; found {
		err = json.Unmarshal(raw, &a.ErrCode)
		if err != nil {
			return fmt.Errorf("error reading 'err_code': %w", err)
		}
		delete(object, "err_code")
	}

	if raw, found := object["hw_ver"]; found {
		err = json.Unmarshal(raw, &a.HwVer)
		if err != nil {
			return fmt.Errorf("error reading 'hw_ver': %w", err)
		}
		delete(object, "hw_ver")
	}

	if raw, found := object["model"]; found {
		err = json.Unmarshal(raw, &a.Model)
		if err != nil {
			return fmt.Errorf("error reading 'model': %w", err)
		}
		delete(object, "model")
	}

	if raw, found := object["on_time"]; found {
		err = json.Unmarshal(raw, &a.OnTime)
		if err != nil {
			return fmt.Errorf("error reading 'on_time': %w", err)
		}
		delete(object, "on_time")
	}

	if raw, found := object["relay_state"]; found {
		err = json.Unmarshal(raw, &a.RelayState)
		if err != nil {
			return fmt.Errorf("error reading 'relay_state': %w", err)
		}
		delete(object, "relay_state")
	}

	if raw, found := object["sw_ver"]; found {
		err = json.Unmarshal(raw, &a.SwVer)
		if err != nil {
			return fmt.Errorf("error reading 'sw_ver': %w", err)
		}
		delete(object, "sw_ver")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SysInfo to handle AdditionalProperties
func (a SysInfo) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Alias != nil {
		object["alias"], err = json.Marshal(a.Alias)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'alias': %w", err)
		}
	}

	if a.DeviceId != nil {
		object["deviceId"], err = json.Marshal(a.DeviceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceId': %w", err)
		}
	}

	if a.ErrCode != nil {
		object["err_code"], err = json.Marshal(a.ErrCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_code': %w", err)
		}
	}

	if a.HwVer != nil {
		object["hw_ver"], err = json.Marshal(a.HwVer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hw_ver': %w", err)
		}
	}

	if a.Model != nil {
		object["model"], err = json.Marshal(a.Model)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'model': %w", err)
		}
	}

	if a.OnTime != nil {
		object["on_time"], err = json.Marshal(a.OnTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'on_time': %w", err)
		}
	}

	if a.RelayState != nil {
		object["relay_state"], err = json.Marshal(a.RelayState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'relay_state': %w", err)
		}
	}

	if a.SwVer != nil {
		object["sw_ver"], err = json.Marshal(a.SwVer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sw_ver': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SystemCommandResult. Returns the specified
// element and whether it was found
func (a SystemCommandResult) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SystemCommandResult
func (a *SystemCommandResult) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SystemCommandResult to handle AdditionalProperties
func (a *SystemCommandResult) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["system"]; found {
		err = json.Unmarshal(raw, &a.System)
		if err != nil {
			return fmt.Errorf("error reading 'system': %w", err)
		}
		delete(object, "system")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SystemCommandResult to handle AdditionalProperties
func (a SystemCommandResult) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.System != nil {
		object["system"], err = json.Marshal(a.System)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'system': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SystemCommandResult_System. Returns the specified
// element and whether it was found
func (a SystemCommandResult_System) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SystemCommandResult_System
func (a *SystemCommandResult_System) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SystemCommandResult_System to handle AdditionalProperties
func (a *SystemCommandResult_System) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["get_sysinfo"]; found {
		err = json.Unmarshal(raw, &a.GetSysinfo)
		if err != nil {
			return fmt.Errorf("error reading 'get_sysinfo': %w", err)
		}
		delete(object, "get_sysinfo")
	}

	if raw, found := object["reboot"]; found {
		err = json.Unmarshal(raw, &a.Reboot)
		if err != nil {
			return fmt.Errorf("error reading 'reboot': %w", err)
		}
		delete(object, "reboot")
	}

	if raw, found := object["set_dev_alias"]; found {
		err = json.Unmarshal(raw, &a.SetDevAlias)
		if err != nil {
			return fmt.Errorf("error reading 'set_dev_alias': %w", err)
		}
		delete(object, "set_dev_alias")
	}

	if raw, found := object["set_relay_state"]; found {
		err = json.Unmarshal(raw, &a.SetRelayState)
		if err != nil {
			return fmt.Errorf("error reading 'set_relay_state': %w", err)
		}
		delete(object, "set_relay_state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SystemCommandResult_System to handle AdditionalProperties
func (a SystemCommandResult_System) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.GetSysinfo != nil {
		object["get_sysinfo"], err = json.Marshal(a.GetSysinfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'get_sysinfo': %w", err)
		}
	}

	if a.Reboot != nil {
		object["reboot"], err = json.Marshal(a.Reboot)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reboot': %w", err)
		}
	}

	if a.SetDevAlias != nil {
		object["set_dev_alias"], err = json.Marshal(a.SetDevAlias)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'set_dev_alias': %w", err)
		}
	}

	if a.SetRelayState != nil {
		object["set_relay_state"], err = json.Marshal(a.SetRelayState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'set_relay_state': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsLoginCloudRequest returns the union data inside the CloudRequest as a LoginCloudRequest
func (t CloudRequest) AsLoginCloudRequest() (LoginCloudRequest, error) {
	var body LoginCloudRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLoginCloudRequest overwrites any union data inside the CloudRequest as the provided LoginCloudRequest
func (t *CloudRequest) FromLoginCloudRequest(v LoginCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"login"}`))
	t.union = b
	return err
}

// MergeLoginCloudRequest performs a merge with any union data inside the CloudRequest, using the provided LoginCloudRequest
func (t *CloudRequest) MergeLoginCloudRequest(v LoginCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"login"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGetDeviceListCloudRequest returns the union data inside the CloudRequest as a GetDeviceListCloudRequest
func (t CloudRequest) AsGetDeviceListCloudRequest() (GetDeviceListCloudRequest, error) {
	var body GetDeviceListCloudRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetDeviceListCloudRequest overwrites any union data inside the CloudRequest as the provided GetDeviceListCloudRequest
func (t *CloudRequest) FromGetDeviceListCloudRequest(v GetDeviceListCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"getDeviceList"}`))
	t.union = b
	return err
}

// MergeGetDeviceListCloudRequest performs a merge with any union data inside the CloudRequest, using the provided GetDeviceListCloudRequest
func (t *CloudRequest) MergeGetDeviceListCloudRequest(v GetDeviceListCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"getDeviceList"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPassthroughCloudRequest returns the union data inside the CloudRequest as a PassthroughCloudRequest
func (t CloudRequest) AsPassthroughCloudRequest() (PassthroughCloudRequest, error) {
	var body PassthroughCloudRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPassthroughCloudRequest overwrites any union data inside the CloudRequest as the provided PassthroughCloudRequest
func (t *CloudRequest) FromPassthroughCloudRequest(v PassthroughCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"passthrough"}`))
	t.union = b
	return err
}

// MergePassthroughCloudRequest performs a merge with any union data inside the CloudRequest, using the provided PassthroughCloudRequest
func (t *CloudRequest) MergePassthroughCloudRequest(v PassthroughCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"passthrough"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CloudRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"method"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CloudRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "getDeviceList":
		return t.AsGetDeviceListCloudRequest()
	case "login":
		return t.AsLoginCloudRequest()
	case "passthrough":
		return t.AsPassthroughCloudRequest()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CloudRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CloudRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsLoginResponse returns the union data inside the CloudResponseEnvelope as a LoginResponse
func (t CloudResponseEnvelope) AsLoginResponse() (LoginResponse, error) {
	var body LoginResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLoginResponse overwrites any union data inside the CloudResponseEnvelope as the provided LoginResponse
func (t *CloudResponseEnvelope) FromLoginResponse(v LoginResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLoginResponse performs a merge with any union data inside the CloudResponseEnvelope, using the provided LoginResponse
func (t *CloudResponseEnvelope) MergeLoginResponse(v LoginResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceListResponse returns the union data inside the CloudResponseEnvelope as a DeviceListResponse
func (t CloudResponseEnvelope) AsDeviceListResponse() (DeviceListResponse, error) {
	var body DeviceListResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceListResponse overwrites any union data inside the CloudResponseEnvelope as the provided DeviceListResponse
func (t *CloudResponseEnvelope) FromDeviceListResponse(v DeviceListResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceListResponse performs a merge with any union data inside the CloudResponseEnvelope, using the provided DeviceListResponse
func (t *CloudResponseEnvelope) MergeDeviceListResponse(v DeviceListResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPassthroughResponse returns the union data inside the CloudResponseEnvelope as a PassthroughResponse
func (t CloudResponseEnvelope) AsPassthroughResponse() (PassthroughResponse, error) {
	var body PassthroughResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPassthroughResponse overwrites any union data inside the CloudResponseEnvelope as the provided PassthroughResponse
func (t *CloudResponseEnvelope) FromPassthroughResponse(v PassthroughResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePassthroughResponse performs a merge with any union data inside the CloudResponseEnvelope, using the provided PassthroughResponse
func (t *CloudResponseEnvelope) MergePassthroughResponse(v PassthroughResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCloudErrorResponse returns the union data inside the CloudResponseEnvelope as a CloudErrorResponse
func (t CloudResponseEnvelope) AsCloudErrorResponse() (CloudErrorResponse, error) {
	var body CloudErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCloudErrorResponse overwrites any union data inside the CloudResponseEnvelope as the provided CloudErrorResponse
func (t *CloudResponseEnvelope) FromCloudErrorResponse(v CloudErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCloudErrorResponse performs a merge with any union data inside the CloudResponseEnvelope, using the provided CloudErrorResponse
func (t *CloudResponseEnvelope) MergeCloudErrorResponse(v CloudErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CloudResponseEnvelope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CloudResponseEnvelope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSystemGetSysInfoCommand returns the union data inside the PassthroughCommand as a SystemGetSysInfoCommand
func (t PassthroughCommand) AsSystemGetSysInfoCommand() (SystemGetSysInfoCommand, error) {
	var body SystemGetSysInfoCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemGetSysInfoCommand overwrites any union data inside the PassthroughCommand as the provided SystemGetSysInfoCommand
func (t *PassthroughCommand) FromSystemGetSysInfoCommand(v SystemGetSysInfoCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemGetSysInfoCommand performs a merge with any union data inside the PassthroughCommand, using the provided SystemGetSysInfoCommand
func (t *PassthroughCommand) MergeSystemGetSysInfoCommand(v SystemGetSysInfoCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSystemSetRelayStateCommand returns the union data inside the PassthroughCommand as a SystemSetRelayStateCommand
func (t PassthroughCommand) AsSystemSetRelayStateCommand() (SystemSetRelayStateCommand, error) {
	var body SystemSetRelayStateCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemSetRelayStateCommand overwrites any union data inside the PassthroughCommand as the provided SystemSetRelayStateCommand
func (t *PassthroughCommand) FromSystemSetRelayStateCommand(v SystemSetRelayStateCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemSetRelayStateCommand performs a merge with any union data inside the PassthroughCommand, using the provided SystemSetRelayStateCommand
func (t *PassthroughCommand) MergeSystemSetRelayStateCommand(v SystemSetRelayStateCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSystemRebootCommand returns the union data inside the PassthroughCommand as a SystemRebootCommand
func (t PassthroughCommand) AsSystemRebootCommand() (SystemRebootCommand, error) {
	var body SystemRebootCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemRebootCommand overwrites any union data inside the PassthroughCommand as the provided SystemRebootCommand
func (t *PassthroughCommand) FromSystemRebootCommand(v SystemRebootCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemRebootCommand performs a merge with any union data inside the PassthroughCommand, using the provided SystemRebootCommand
func (t *PassthroughCommand) MergeSystemRebootCommand(v SystemRebootCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSystemSetDevAliasCommand returns the union data inside the PassthroughCommand as a SystemSetDevAliasCommand
func (t PassthroughCommand) AsSystemSetDevAliasCommand() (SystemSetDevAliasCommand, error) {
	var body SystemSetDevAliasCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemSetDevAliasCommand overwrites any union data inside the PassthroughCommand as the provided SystemSetDevAliasCommand
func (t *PassthroughCommand) FromSystemSetDevAliasCommand(v SystemSetDevAliasCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemSetDevAliasCommand performs a merge with any union data inside the PassthroughCommand, using the provided SystemSetDevAliasCommand
func (t *PassthroughCommand) MergeSystemSetDevAliasCommand(v SystemSetDevAliasCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLightingGetLightStateCommand returns the union data inside the PassthroughCommand as a LightingGetLightStateCommand
func (t PassthroughCommand) AsLightingGetLightStateCommand() (LightingGetLightStateCommand, error) {
	var body LightingGetLightStateCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLightingGetLightStateCommand overwrites any union data inside the PassthroughCommand as the provided LightingGetLightStateCommand
func (t *PassthroughCommand) FromLightingGetLightStateCommand(v LightingGetLightStateCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLightingGetLightStateCommand performs a merge with any union data inside the PassthroughCommand, using the provided LightingGetLightStateCommand
func (t *PassthroughCommand) MergeLightingGetLightStateCommand(v LightingGetLightStateCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLightingTransitionLightStateCommand returns the union data inside the PassthroughCommand as a LightingTransitionLightStateCommand
func (t PassthroughCommand) AsLightingTransitionLightStateCommand() (LightingTransitionLightStateCommand, error) {
	var body LightingTransitionLightStateCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLightingTransitionLightStateCommand overwrites any union data inside the PassthroughCommand as the provided LightingTransitionLightStateCommand
func (t *PassthroughCommand) FromLightingTransitionLightStateCommand(v LightingTransitionLightStateCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLightingTransitionLightStateCommand performs a merge with any union data inside the PassthroughCommand, using the provided LightingTransitionLightStateCommand
func (t *PassthroughCommand) MergeLightingTransitionLightStateCommand(v LightingTransitionLightStateCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PassthroughCommand) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PassthroughCommand) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSystemCommandResult returns the union data inside the PassthroughCommandResult as a SystemCommandResult
func (t PassthroughCommandResult) AsSystemCommandResult() (SystemCommandResult, error) {
	var body SystemCommandResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemCommandResult overwrites any union data inside the PassthroughCommandResult as the provided SystemCommandResult
func (t *PassthroughCommandResult) FromSystemCommandResult(v SystemCommandResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemCommandResult performs a merge with any union data inside the PassthroughCommandResult, using the provided SystemCommandResult
func (t *PassthroughCommandResult) MergeSystemCommandResult(v SystemCommandResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLightingCommandResult returns the union data inside the PassthroughCommandResult as a LightingCommandResult
func (t PassthroughCommandResult) AsLightingCommandResult() (LightingCommandResult, error) {
	var body LightingCommandResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLightingCommandResult overwrites any union data inside the PassthroughCommandResult as the provided LightingCommandResult
func (t *PassthroughCommandResult) FromLightingCommandResult(v LightingCommandResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLightingCommandResult performs a merge with any union data inside the PassthroughCommandResult, using the provided LightingCommandResult
func (t *PassthroughCommandResult) MergeLightingCommandResult(v LightingCommandResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceCommandError returns the union data inside the PassthroughCommandResult as a DeviceCommandError
func (t PassthroughCommandResult) AsDeviceCommandError() (DeviceCommandError, error) {
	var body DeviceCommandError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceCommandError overwrites any union data inside the PassthroughCommandResult as the provided DeviceCommandError
func (t *PassthroughCommandResult) FromDeviceCommandError(v DeviceCommandError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceCommandError performs a merge with any union data inside the PassthroughCommandResult, using the provided DeviceCommandError
func (t *PassthroughCommandResult) MergeDeviceCommandError(v DeviceCommandError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PassthroughCommandResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PassthroughCommandResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
