// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dependencymodels

// Defines values for LoginCloudRequestMethod.
const (
	Login LoginCloudRequestMethod = "login"
)

// Valid indicates whether the value is a known member of the LoginCloudRequestMethod enum.
func (e LoginCloudRequestMethod) Valid() bool {
	switch e {
	case Login:
		return true
	default:
		return false
	}
}

// Defines values for LoginParamsAppType.
const (
	TapoAndroid LoginParamsAppType = "Tapo_Android"
)

// Valid indicates whether the value is a known member of the LoginParamsAppType enum.
func (e LoginParamsAppType) Valid() bool {
	switch e {
	case TapoAndroid:
		return true
	default:
		return false
	}
}

// Defines values for LoginParamsTerminalUUID.
const (
	GoTplinkClient LoginParamsTerminalUUID = "go-tplink-client"
)

// Valid indicates whether the value is a known member of the LoginParamsTerminalUUID enum.
func (e LoginParamsTerminalUUID) Valid() bool {
	switch e {
	case GoTplinkClient:
		return true
	default:
		return false
	}
}

// LoginCloudRequest defines model for LoginCloudRequest.
type LoginCloudRequest struct {
	Method LoginCloudRequestMethod `json:"method"`
	Params LoginParams             `json:"params"`
}

// LoginCloudRequestMethod defines model for LoginCloudRequest.Method.
type LoginCloudRequestMethod string

// LoginParams defines model for LoginParams.
type LoginParams struct {
	// AppType Fixed appType value sent by this client.
	AppType LoginParamsAppType `json:"appType"`

	// CloudPassword Account password supplied to Login.
	CloudPassword *string `json:"cloudPassword,omitempty"`

	// CloudUserName Account email supplied to Login.
	CloudUserName string `json:"cloudUserName"`

	// TerminalUUID Fixed terminalUUID value sent by this client.
	TerminalUUID LoginParamsTerminalUUID `json:"terminalUUID"`
}

// LoginParamsAppType Fixed appType value sent by this client.
type LoginParamsAppType string

// LoginParamsTerminalUUID Fixed terminalUUID value sent by this client.
type LoginParamsTerminalUUID string

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// ErrorCode Zero indicates success. Known cloud failures include -20004 (rate limit), -20651 (expired token), -20104 (parameter error), and -20601 (authentication error). Other non-zero codes may occur.
	ErrorCode *int `json:"error_code,omitempty"`

	// Msg Optional cloud error message.
	Msg    *string      `json:"msg,omitempty"`
	Result *LoginResult `json:"result,omitempty"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	AccountId   *string `json:"accountId,omitempty"`
	CountryCode *string `json:"countryCode,omitempty"`
	Email       *string `json:"email,omitempty"`
	RegTime     *string `json:"regTime,omitempty"`

	// Token Opaque session token for subsequent authenticated requests.
	Token *string `json:"token,omitempty"`
}
