// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// CloudErrorResponse defines model for CloudErrorResponse.
type CloudErrorResponse struct {
	// ErrorCode Non-zero cloud error code. The implementation maps several known codes and preserves other non-zero codes as generic errors.
	ErrorCode int `json:"error_code"`

	// Msg Optional cloud error message.
	Msg *string `json:"msg,omitempty"`
}

// CloudRequest Discriminated request envelope for the single POST endpoint.
type CloudRequest struct {
	union json.RawMessage
}

// CloudResponse defines model for CloudResponse.
type CloudResponse struct {
	// ErrorCode Zero indicates success. Known cloud failures include -20004 (rate limit), -20651 (expired token), -20104 (parameter error), and -20601 (authentication error). Other non-zero codes may occur.
	ErrorCode *int `json:"error_code,omitempty"`

	// Msg Optional cloud error message.
	Msg *string `json:"msg,omitempty"`
}

// CloudResponseEnvelope Expected result or cloud-error shape. Responses have no method discriminator, and response models are permissive because the client unmarshals into zero-valued Go fields; the request method identifies the expected result.
type CloudResponseEnvelope struct {
	union json.RawMessage
}

// AsLoginCloudRequest returns the union data inside the CloudRequest as a LoginCloudRequest
func (t CloudRequest) AsLoginCloudRequest() (LoginCloudRequest, error) {
	var body LoginCloudRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLoginCloudRequest overwrites any union data inside the CloudRequest as the provided LoginCloudRequest
func (t *CloudRequest) FromLoginCloudRequest(v LoginCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"login"}`))
	t.union = b
	return err
}

// MergeLoginCloudRequest performs a merge with any union data inside the CloudRequest, using the provided LoginCloudRequest
func (t *CloudRequest) MergeLoginCloudRequest(v LoginCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"login"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGetDeviceListCloudRequest returns the union data inside the CloudRequest as a GetDeviceListCloudRequest
func (t CloudRequest) AsGetDeviceListCloudRequest() (GetDeviceListCloudRequest, error) {
	var body GetDeviceListCloudRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetDeviceListCloudRequest overwrites any union data inside the CloudRequest as the provided GetDeviceListCloudRequest
func (t *CloudRequest) FromGetDeviceListCloudRequest(v GetDeviceListCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"getDeviceList"}`))
	t.union = b
	return err
}

// MergeGetDeviceListCloudRequest performs a merge with any union data inside the CloudRequest, using the provided GetDeviceListCloudRequest
func (t *CloudRequest) MergeGetDeviceListCloudRequest(v GetDeviceListCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"getDeviceList"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPassthroughCloudRequest returns the union data inside the CloudRequest as a PassthroughCloudRequest
func (t CloudRequest) AsPassthroughCloudRequest() (PassthroughCloudRequest, error) {
	var body PassthroughCloudRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPassthroughCloudRequest overwrites any union data inside the CloudRequest as the provided PassthroughCloudRequest
func (t *CloudRequest) FromPassthroughCloudRequest(v PassthroughCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"passthrough"}`))
	t.union = b
	return err
}

// MergePassthroughCloudRequest performs a merge with any union data inside the CloudRequest, using the provided PassthroughCloudRequest
func (t *CloudRequest) MergePassthroughCloudRequest(v PassthroughCloudRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"method":"passthrough"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CloudRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"method"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CloudRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "getDeviceList":
		return t.AsGetDeviceListCloudRequest()
	case "login":
		return t.AsLoginCloudRequest()
	case "passthrough":
		return t.AsPassthroughCloudRequest()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CloudRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CloudRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsLoginResponse returns the union data inside the CloudResponseEnvelope as a LoginResponse
func (t CloudResponseEnvelope) AsLoginResponse() (LoginResponse, error) {
	var body LoginResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLoginResponse overwrites any union data inside the CloudResponseEnvelope as the provided LoginResponse
func (t *CloudResponseEnvelope) FromLoginResponse(v LoginResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLoginResponse performs a merge with any union data inside the CloudResponseEnvelope, using the provided LoginResponse
func (t *CloudResponseEnvelope) MergeLoginResponse(v LoginResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceListResponse returns the union data inside the CloudResponseEnvelope as a DeviceListResponse
func (t CloudResponseEnvelope) AsDeviceListResponse() (DeviceListResponse, error) {
	var body DeviceListResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceListResponse overwrites any union data inside the CloudResponseEnvelope as the provided DeviceListResponse
func (t *CloudResponseEnvelope) FromDeviceListResponse(v DeviceListResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceListResponse performs a merge with any union data inside the CloudResponseEnvelope, using the provided DeviceListResponse
func (t *CloudResponseEnvelope) MergeDeviceListResponse(v DeviceListResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPassthroughResponse returns the union data inside the CloudResponseEnvelope as a PassthroughResponse
func (t CloudResponseEnvelope) AsPassthroughResponse() (PassthroughResponse, error) {
	var body PassthroughResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPassthroughResponse overwrites any union data inside the CloudResponseEnvelope as the provided PassthroughResponse
func (t *CloudResponseEnvelope) FromPassthroughResponse(v PassthroughResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePassthroughResponse performs a merge with any union data inside the CloudResponseEnvelope, using the provided PassthroughResponse
func (t *CloudResponseEnvelope) MergePassthroughResponse(v PassthroughResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCloudErrorResponse returns the union data inside the CloudResponseEnvelope as a CloudErrorResponse
func (t CloudResponseEnvelope) AsCloudErrorResponse() (CloudErrorResponse, error) {
	var body CloudErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCloudErrorResponse overwrites any union data inside the CloudResponseEnvelope as the provided CloudErrorResponse
func (t *CloudResponseEnvelope) FromCloudErrorResponse(v CloudErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCloudErrorResponse performs a merge with any union data inside the CloudResponseEnvelope, using the provided CloudErrorResponse
func (t *CloudResponseEnvelope) MergeCloudErrorResponse(v CloudErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CloudResponseEnvelope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CloudResponseEnvelope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
