// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dependencymodels

// SendCloudRequestParams defines parameters for SendCloudRequest.
type SendCloudRequestParams struct {
	// Token Session token. Omit for login; the client requires it for getDeviceList and passthrough.
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// SendCloudRequestJSONRequestBody defines body for SendCloudRequest for application/json ContentType.
type SendCloudRequestJSONRequestBody = CloudRequest
