// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"
)

// Defines values for GetDeviceListCloudRequestMethod.
const (
	GetDeviceList GetDeviceListCloudRequestMethod = "getDeviceList"
)

// Valid indicates whether the value is a known member of the GetDeviceListCloudRequestMethod enum.
func (e GetDeviceListCloudRequestMethod) Valid() bool {
	switch e {
	case GetDeviceList:
		return true
	default:
		return false
	}
}

// Device Cloud device record. The client retains records with unknown deviceType values, but its Go model does not retain fields outside those listed here.
type Device struct {
	// Alias Display name shown to the user.
	Alias        *string `json:"alias,omitempty"`
	AppServerUrl *string `json:"appServerUrl,omitempty"`
	Brightness   *int    `json:"brightness,omitempty"`
	DeviceHwVer  *string `json:"deviceHwVer,omitempty"`

	// DeviceId Pass this value as params.deviceId for passthrough commands.
	DeviceId     *string `json:"deviceId,omitempty"`
	DeviceMac    *string `json:"deviceMac,omitempty"`
	DeviceModel  *string `json:"deviceModel,omitempty"`
	DeviceRegion *string `json:"deviceRegion,omitempty"`

	// DeviceType The client classifies the known plug and bulb values below; other values remain valid and are classified as Other.
	DeviceType   *string `json:"deviceType,omitempty"`
	FwId         *string `json:"fwId,omitempty"`
	FwVer        *string `json:"fwVer,omitempty"`
	HwId         *string `json:"hwId,omitempty"`
	IsSameRegion *bool   `json:"isSameRegion,omitempty"`

	// IsColor Cloud-reported capability flag; 1 indicates color support.
	IsColor *int `json:"is_color,omitempty"`

	// IsDimmable Cloud-reported capability flag; 1 indicates dimming support.
	IsDimmable *int `json:"is_dimmable,omitempty"`

	// IsVariableColorTemp Cloud-reported capability flag; 1 indicates color temperature support.
	IsVariableColorTemp *int    `json:"is_variable_color_temp,omitempty"`
	OemId               *string `json:"oemId,omitempty"`

	// Status Cloud-reported status; interpretation may vary by device.
	Status               *int                   `json:"status,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceListResponse defines model for DeviceListResponse.
type DeviceListResponse struct {
	// ErrorCode Zero indicates success. Known cloud failures include -20004 (rate limit), -20651 (expired token), -20104 (parameter error), and -20601 (authentication error). Other non-zero codes may occur.
	ErrorCode *int `json:"error_code,omitempty"`

	// Msg Optional cloud error message.
	Msg *string `json:"msg,omitempty"`

	// Result The array may be empty. Each element is a cloud device record.
	Result *DeviceListResult `json:"result,omitempty"`
}

// DeviceListResult The array may be empty. Each element is a cloud device record.
type DeviceListResult struct {
	DeviceList *[]Device `json:"deviceList,omitempty"`
}

// GetDeviceListCloudRequest The implemented client sends no params for this method.
type GetDeviceListCloudRequest struct {
	Method GetDeviceListCloudRequestMethod `json:"method"`
}

// GetDeviceListCloudRequestMethod defines model for GetDeviceListCloudRequest.Method.
type GetDeviceListCloudRequestMethod string

// Getter for additional properties for Device. Returns the specified
// element and whether it was found
func (a Device) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Device
func (a *Device) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a *Device) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["alias"]; found {
		err = json.Unmarshal(raw, &a.Alias)
		if err != nil {
			return fmt.Errorf("error reading 'alias': %w", err)
		}
		delete(object, "alias")
	}

	if raw, found := object["appServerUrl"]; found {
		err = json.Unmarshal(raw, &a.AppServerUrl)
		if err != nil {
			return fmt.Errorf("error reading 'appServerUrl': %w", err)
		}
		delete(object, "appServerUrl")
	}

	if raw, found := object["brightness"]; found {
		err = json.Unmarshal(raw, &a.Brightness)
		if err != nil {
			return fmt.Errorf("error reading 'brightness': %w", err)
		}
		delete(object, "brightness")
	}

	if raw, found := object["deviceHwVer"]; found {
		err = json.Unmarshal(raw, &a.DeviceHwVer)
		if err != nil {
			return fmt.Errorf("error reading 'deviceHwVer': %w", err)
		}
		delete(object, "deviceHwVer")
	}

	if raw, found := object["deviceId"]; found {
		err = json.Unmarshal(raw, &a.DeviceId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceId': %w", err)
		}
		delete(object, "deviceId")
	}

	if raw, found := object["deviceMac"]; found {
		err = json.Unmarshal(raw, &a.DeviceMac)
		if err != nil {
			return fmt.Errorf("error reading 'deviceMac': %w", err)
		}
		delete(object, "deviceMac")
	}

	if raw, found := object["deviceModel"]; found {
		err = json.Unmarshal(raw, &a.DeviceModel)
		if err != nil {
			return fmt.Errorf("error reading 'deviceModel': %w", err)
		}
		delete(object, "deviceModel")
	}

	if raw, found := object["deviceRegion"]; found {
		err = json.Unmarshal(raw, &a.DeviceRegion)
		if err != nil {
			return fmt.Errorf("error reading 'deviceRegion': %w", err)
		}
		delete(object, "deviceRegion")
	}

	if raw, found := object["deviceType"]; found {
		err = json.Unmarshal(raw, &a.DeviceType)
		if err != nil {
			return fmt.Errorf("error reading 'deviceType': %w", err)
		}
		delete(object, "deviceType")
	}

	if raw, found := object["fwId"]; found {
		err = json.Unmarshal(raw, &a.FwId)
		if err != nil {
			return fmt.Errorf("error reading 'fwId': %w", err)
		}
		delete(object, "fwId")
	}

	if raw, found := object["fwVer"]; found {
		err = json.Unmarshal(raw, &a.FwVer)
		if err != nil {
			return fmt.Errorf("error reading 'fwVer': %w", err)
		}
		delete(object, "fwVer")
	}

	if raw, found := object["hwId"]; found {
		err = json.Unmarshal(raw, &a.HwId)
		if err != nil {
			return fmt.Errorf("error reading 'hwId': %w", err)
		}
		delete(object, "hwId")
	}

	if raw, found := object["isSameRegion"]; found {
		err = json.Unmarshal(raw, &a.IsSameRegion)
		if err != nil {
			return fmt.Errorf("error reading 'isSameRegion': %w", err)
		}
		delete(object, "isSameRegion")
	}

	if raw, found := object["is_color"]; found {
		err = json.Unmarshal(raw, &a.IsColor)
		if err != nil {
			return fmt.Errorf("error reading 'is_color': %w", err)
		}
		delete(object, "is_color")
	}

	if raw, found := object["is_dimmable"]; found {
		err = json.Unmarshal(raw, &a.IsDimmable)
		if err != nil {
			return fmt.Errorf("error reading 'is_dimmable': %w", err)
		}
		delete(object, "is_dimmable")
	}

	if raw, found := object["is_variable_color_temp"]; found {
		err = json.Unmarshal(raw, &a.IsVariableColorTemp)
		if err != nil {
			return fmt.Errorf("error reading 'is_variable_color_temp': %w", err)
		}
		delete(object, "is_variable_color_temp")
	}

	if raw, found := object["oemId"]; found {
		err = json.Unmarshal(raw, &a.OemId)
		if err != nil {
			return fmt.Errorf("error reading 'oemId': %w", err)
		}
		delete(object, "oemId")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a Device) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Alias != nil {
		object["alias"], err = json.Marshal(a.Alias)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'alias': %w", err)
		}
	}

	if a.AppServerUrl != nil {
		object["appServerUrl"], err = json.Marshal(a.AppServerUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'appServerUrl': %w", err)
		}
	}

	if a.Brightness != nil {
		object["brightness"], err = json.Marshal(a.Brightness)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'brightness': %w", err)
		}
	}

	if a.DeviceHwVer != nil {
		object["deviceHwVer"], err = json.Marshal(a.DeviceHwVer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceHwVer': %w", err)
		}
	}

	if a.DeviceId != nil {
		object["deviceId"], err = json.Marshal(a.DeviceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceId': %w", err)
		}
	}

	if a.DeviceMac != nil {
		object["deviceMac"], err = json.Marshal(a.DeviceMac)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceMac': %w", err)
		}
	}

	if a.DeviceModel != nil {
		object["deviceModel"], err = json.Marshal(a.DeviceModel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceModel': %w", err)
		}
	}

	if a.DeviceRegion != nil {
		object["deviceRegion"], err = json.Marshal(a.DeviceRegion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceRegion': %w", err)
		}
	}

	if a.DeviceType != nil {
		object["deviceType"], err = json.Marshal(a.DeviceType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceType': %w", err)
		}
	}

	if a.FwId != nil {
		object["fwId"], err = json.Marshal(a.FwId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fwId': %w", err)
		}
	}

	if a.FwVer != nil {
		object["fwVer"], err = json.Marshal(a.FwVer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fwVer': %w", err)
		}
	}

	if a.HwId != nil {
		object["hwId"], err = json.Marshal(a.HwId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hwId': %w", err)
		}
	}

	if a.IsSameRegion != nil {
		object["isSameRegion"], err = json.Marshal(a.IsSameRegion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isSameRegion': %w", err)
		}
	}

	if a.IsColor != nil {
		object["is_color"], err = json.Marshal(a.IsColor)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_color': %w", err)
		}
	}

	if a.IsDimmable != nil {
		object["is_dimmable"], err = json.Marshal(a.IsDimmable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_dimmable': %w", err)
		}
	}

	if a.IsVariableColorTemp != nil {
		object["is_variable_color_temp"], err = json.Marshal(a.IsVariableColorTemp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_variable_color_temp': %w", err)
		}
	}

	if a.OemId != nil {
		object["oemId"], err = json.Marshal(a.OemId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'oemId': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
