// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
)

// Defines values for LightTransitionStateOnOff.
const (
	LightTransitionStateOnOffN0 LightTransitionStateOnOff = 0
	LightTransitionStateOnOffN1 LightTransitionStateOnOff = 1
)

// Valid indicates whether the value is a known member of the LightTransitionStateOnOff enum.
func (e LightTransitionStateOnOff) Valid() bool {
	switch e {
	case LightTransitionStateOnOffN0:
		return true
	case LightTransitionStateOnOffN1:
		return true
	default:
		return false
	}
}

// Defines values for LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState.
const (
	LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightStateEmpty LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState = ""
)

// Valid indicates whether the value is a known member of the LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState enum.
func (e LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState) Valid() bool {
	switch e {
	case LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightStateEmpty:
		return true
	default:
		return false
	}
}

// Defines values for PassthroughCloudRequestMethod.
const (
	Passthrough PassthroughCloudRequestMethod = "passthrough"
)

// Valid indicates whether the value is a known member of the PassthroughCloudRequestMethod enum.
func (e PassthroughCloudRequestMethod) Valid() bool {
	switch e {
	case Passthrough:
		return true
	default:
		return false
	}
}

// Defines values for SystemGetSysInfoCommandSystemGetSysinfo.
const (
	SystemGetSysInfoCommandSystemGetSysinfoEmpty SystemGetSysInfoCommandSystemGetSysinfo = ""
)

// Valid indicates whether the value is a known member of the SystemGetSysInfoCommandSystemGetSysinfo enum.
func (e SystemGetSysInfoCommandSystemGetSysinfo) Valid() bool {
	switch e {
	case SystemGetSysInfoCommandSystemGetSysinfoEmpty:
		return true
	default:
		return false
	}
}

// Defines values for SystemRebootCommandSystemRebootDelay.
const (
	SystemRebootCommandSystemRebootDelayN1 SystemRebootCommandSystemRebootDelay = 1
)

// Valid indicates whether the value is a known member of the SystemRebootCommandSystemRebootDelay enum.
func (e SystemRebootCommandSystemRebootDelay) Valid() bool {
	switch e {
	case SystemRebootCommandSystemRebootDelayN1:
		return true
	default:
		return false
	}
}

// Defines values for SystemSetRelayStateCommandSystemSetRelayStateState.
const (
	SystemSetRelayStateCommandSystemSetRelayStateStateN0 SystemSetRelayStateCommandSystemSetRelayStateState = 0
	SystemSetRelayStateCommandSystemSetRelayStateStateN1 SystemSetRelayStateCommandSystemSetRelayStateState = 1
)

// Valid indicates whether the value is a known member of the SystemSetRelayStateCommandSystemSetRelayStateState enum.
func (e SystemSetRelayStateCommandSystemSetRelayStateState) Valid() bool {
	switch e {
	case SystemSetRelayStateCommandSystemSetRelayStateStateN0:
		return true
	case SystemSetRelayStateCommandSystemSetRelayStateStateN1:
		return true
	default:
		return false
	}
}

// CommandAcknowledgement defines model for CommandAcknowledgement.
type CommandAcknowledgement struct {
	// ErrCode Zero indicates success; -1 indicates an unsupported command in the implemented client.
	ErrCode              *int                   `json:"err_code,omitempty"`
	ErrMsg               *string                `json:"err_msg,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceCommandError defines model for DeviceCommandError.
type DeviceCommandError struct {
	// ErrCode Non-zero device-level error code; -1 indicates an unsupported command.
	ErrCode              int                    `json:"err_code"`
	ErrMsg               *string                `json:"err_msg,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LightState defines model for LightState.
type LightState struct {
	Brightness           *int                   `json:"brightness,omitempty"`
	ColorTemp            *int                   `json:"color_temp,omitempty"`
	ErrCode              *int                   `json:"err_code,omitempty"`
	Hue                  *int                   `json:"hue,omitempty"`
	Mode                 *string                `json:"mode,omitempty"`
	OnOff                *int                   `json:"on_off,omitempty"`
	Saturation           *int                   `json:"saturation,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LightTransitionState State values accepted by SetLightState. Other properties may be sent by the generic method; device support depends on its capabilities.
type LightTransitionState struct {
	// Brightness Brightness from 0 through 100.
	Brightness *int `json:"brightness,omitempty"`

	// ColorTemp Color temperature in Kelvin; supported values depend on the device.
	ColorTemp *int `json:"color_temp,omitempty"`

	// Hue Hue from 0 through 360 degrees.
	Hue *int `json:"hue,omitempty"`

	// OnOff 1 turns the bulb on; 0 turns it off.
	OnOff *LightTransitionStateOnOff `json:"on_off,omitempty"`

	// Saturation Saturation from 0 through 100.
	Saturation           *int                   `json:"saturation,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LightTransitionStateOnOff 1 turns the bulb on; 0 turns it off.
type LightTransitionStateOnOff int

// LightingCommandResult defines model for LightingCommandResult.
type LightingCommandResult struct {
	SmartlifeIotSmartbulbLightingservice *LightingCommandResult_SmartlifeIotSmartbulbLightingservice `json:"smartlife.iot.smartbulb.lightingservice,omitempty"`
	AdditionalProperties                 map[string]interface{}                                      `json:"-"`
}

// LightingCommandResult_SmartlifeIotSmartbulbLightingservice defines model for LightingCommandResult.SmartlifeIotSmartbulbLightingservice.
type LightingCommandResult_SmartlifeIotSmartbulbLightingservice struct {
	GetLightState        *LightState             `json:"get_light_state,omitempty"`
	TransitionLightState *CommandAcknowledgement `json:"transition_light_state,omitempty"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// LightingGetLightStateCommand defines model for LightingGetLightStateCommand.
type LightingGetLightStateCommand struct {
	SmartlifeIotSmartbulbLightingservice struct {
		// GetLightState Empty string for the read command.
		GetLightState LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState `json:"get_light_state"`
	} `json:"smartlife.iot.smartbulb.lightingservice"`
}

// LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState Empty string for the read command.
type LightingGetLightStateCommandSmartlifeIotSmartbulbLightingserviceGetLightState string

// LightingTransitionLightStateCommand defines model for LightingTransitionLightStateCommand.
type LightingTransitionLightStateCommand struct {
	SmartlifeIotSmartbulbLightingservice struct {
		// TransitionLightState State values accepted by SetLightState. Other properties may be sent by the generic method; device support depends on its capabilities.
		TransitionLightState *LightTransitionState `json:"transition_light_state"`
	} `json:"smartlife.iot.smartbulb.lightingservice"`
}

// PassthroughCloudRequest defines model for PassthroughCloudRequest.
type PassthroughCloudRequest struct {
	Method PassthroughCloudRequestMethod `json:"method"`
	Params PassthroughParams             `json:"params"`
}

// PassthroughCloudRequestMethod defines model for PassthroughCloudRequest.Method.
type PassthroughCloudRequestMethod string

// PassthroughCommand Inner JSON value after decoding params.requestData. The client sends one command under one namespace per request.
type PassthroughCommand struct {
	union json.RawMessage
}

// PassthroughCommandResult Inner JSON value after decoding result.responseData.
type PassthroughCommandResult struct {
	union json.RawMessage
}

// PassthroughParams defines model for PassthroughParams.
type PassthroughParams struct {
	// DeviceId Device identifier from the device-list result.
	DeviceId string `json:"deviceId"`

	// RequestData JSON-encoded string containing one command object. Decode the string
	// to see the PassthroughCommand schema; do not send that object in
	// place of the string. The Guides list the fields for each command.
	RequestData string `json:"requestData"`
}

// PassthroughResponse defines model for PassthroughResponse.
type PassthroughResponse struct {
	// ErrorCode Zero indicates success. Known cloud failures include -20004 (rate limit), -20651 (expired token), -20104 (parameter error), and -20601 (authentication error). Other non-zero codes may occur.
	ErrorCode *int `json:"error_code,omitempty"`

	// Msg Optional cloud error message.
	Msg    *string            `json:"msg,omitempty"`
	Result *PassthroughResult `json:"result,omitempty"`
}

// PassthroughResult defines model for PassthroughResult.
type PassthroughResult struct {
	// ResponseData JSON-encoded device response. Decode the string to interpret
	// PassthroughCommandResult. Device errors may also appear at the top level.
	ResponseData *string `json:"responseData,omitempty"`
}

// SysInfo defines model for SysInfo.
type SysInfo struct {
	Alias                *string                `json:"alias,omitempty"`
	DeviceId             *string                `json:"deviceId,omitempty"`
	ErrCode              *int                   `json:"err_code,omitempty"`
	HwVer                *string                `json:"hw_ver,omitempty"`
	Model                *string                `json:"model,omitempty"`
	OnTime               *int                   `json:"on_time,omitempty"`
	RelayState           *int                   `json:"relay_state,omitempty"`
	SwVer                *string                `json:"sw_ver,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SystemCommandResult defines model for SystemCommandResult.
type SystemCommandResult struct {
	System               *SystemCommandResult_System `json:"system,omitempty"`
	AdditionalProperties map[string]interface{}      `json:"-"`
}

// SystemCommandResult_System defines model for SystemCommandResult.System.
type SystemCommandResult_System struct {
	GetSysinfo           *SysInfo                `json:"get_sysinfo,omitempty"`
	Reboot               *CommandAcknowledgement `json:"reboot,omitempty"`
	SetDevAlias          *CommandAcknowledgement `json:"set_dev_alias,omitempty"`
	SetRelayState        *CommandAcknowledgement `json:"set_relay_state,omitempty"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// SystemGetSysInfoCommand defines model for SystemGetSysInfoCommand.
type SystemGetSysInfoCommand struct {
	System struct {
		// GetSysinfo Empty string for the read command.
		GetSysinfo SystemGetSysInfoCommandSystemGetSysinfo `json:"get_sysinfo"`
	} `json:"system"`
}

// SystemGetSysInfoCommandSystemGetSysinfo Empty string for the read command.
type SystemGetSysInfoCommandSystemGetSysinfo string

// SystemRebootCommand defines model for SystemRebootCommand.
type SystemRebootCommand struct {
	System struct {
		Reboot struct {
			// Delay The implemented client sends a one-second delay.
			Delay SystemRebootCommandSystemRebootDelay `json:"delay"`
		} `json:"reboot"`
	} `json:"system"`
}

// SystemRebootCommandSystemRebootDelay The implemented client sends a one-second delay.
type SystemRebootCommandSystemRebootDelay int

// SystemSetDevAliasCommand defines model for SystemSetDevAliasCommand.
type SystemSetDevAliasCommand struct {
	System struct {
		SetDevAlias struct {
			Alias string `json:"alias"`
		} `json:"set_dev_alias"`
	} `json:"system"`
}

// SystemSetRelayStateCommand defines model for SystemSetRelayStateCommand.
type SystemSetRelayStateCommand struct {
	System struct {
		SetRelayState struct {
			// State 1 turns the relay on; 0 turns it off.
			State SystemSetRelayStateCommandSystemSetRelayStateState `json:"state"`
		} `json:"set_relay_state"`
	} `json:"system"`
}

// SystemSetRelayStateCommandSystemSetRelayStateState 1 turns the relay on; 0 turns it off.
type SystemSetRelayStateCommandSystemSetRelayStateState int

// Getter for additional properties for CommandAcknowledgement. Returns the specified
// element and whether it was found
func (a CommandAcknowledgement) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CommandAcknowledgement
func (a *CommandAcknowledgement) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CommandAcknowledgement to handle AdditionalProperties
func (a *CommandAcknowledgement) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["err_code"]; found {
		err = json.Unmarshal(raw, &a.ErrCode)
		if err != nil {
			return fmt.Errorf("error reading 'err_code': %w", err)
		}
		delete(object, "err_code")
	}

	if raw, found := object["err_msg"]; found {
		err = json.Unmarshal(raw, &a.ErrMsg)
		if err != nil {
			return fmt.Errorf("error reading 'err_msg': %w", err)
		}
		delete(object, "err_msg")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CommandAcknowledgement to handle AdditionalProperties
func (a CommandAcknowledgement) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ErrCode != nil {
		object["err_code"], err = json.Marshal(a.ErrCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_code': %w", err)
		}
	}

	if a.ErrMsg != nil {
		object["err_msg"], err = json.Marshal(a.ErrMsg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_msg': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DeviceCommandError. Returns the specified
// element and whether it was found
func (a DeviceCommandError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceCommandError
func (a *DeviceCommandError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceCommandError to handle AdditionalProperties
func (a *DeviceCommandError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["err_code"]; found {
		err = json.Unmarshal(raw, &a.ErrCode)
		if err != nil {
			return fmt.Errorf("error reading 'err_code': %w", err)
		}
		delete(object, "err_code")
	}

	if raw, found := object["err_msg"]; found {
		err = json.Unmarshal(raw, &a.ErrMsg)
		if err != nil {
			return fmt.Errorf("error reading 'err_msg': %w", err)
		}
		delete(object, "err_msg")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceCommandError to handle AdditionalProperties
func (a DeviceCommandError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["err_code"], err = json.Marshal(a.ErrCode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'err_code': %w", err)
	}

	if a.ErrMsg != nil {
		object["err_msg"], err = json.Marshal(a.ErrMsg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_msg': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LightState. Returns the specified
// element and whether it was found
func (a LightState) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LightState
func (a *LightState) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LightState to handle AdditionalProperties
func (a *LightState) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["brightness"]; found {
		err = json.Unmarshal(raw, &a.Brightness)
		if err != nil {
			return fmt.Errorf("error reading 'brightness': %w", err)
		}
		delete(object, "brightness")
	}

	if raw, found := object["color_temp"]; found {
		err = json.Unmarshal(raw, &a.ColorTemp)
		if err != nil {
			return fmt.Errorf("error reading 'color_temp': %w", err)
		}
		delete(object, "color_temp")
	}

	if raw, found := object["err_code"]; found {
		err = json.Unmarshal(raw, &a.ErrCode)
		if err != nil {
			return fmt.Errorf("error reading 'err_code': %w", err)
		}
		delete(object, "err_code")
	}

	if raw, found := object["hue"]; found {
		err = json.Unmarshal(raw, &a.Hue)
		if err != nil {
			return fmt.Errorf("error reading 'hue': %w", err)
		}
		delete(object, "hue")
	}

	if raw, found := object["mode"]; found {
		err = json.Unmarshal(raw, &a.Mode)
		if err != nil {
			return fmt.Errorf("error reading 'mode': %w", err)
		}
		delete(object, "mode")
	}

	if raw, found := object["on_off"]; found {
		err = json.Unmarshal(raw, &a.OnOff)
		if err != nil {
			return fmt.Errorf("error reading 'on_off': %w", err)
		}
		delete(object, "on_off")
	}

	if raw, found := object["saturation"]; found {
		err = json.Unmarshal(raw, &a.Saturation)
		if err != nil {
			return fmt.Errorf("error reading 'saturation': %w", err)
		}
		delete(object, "saturation")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LightState to handle AdditionalProperties
func (a LightState) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Brightness != nil {
		object["brightness"], err = json.Marshal(a.Brightness)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'brightness': %w", err)
		}
	}

	if a.ColorTemp != nil {
		object["color_temp"], err = json.Marshal(a.ColorTemp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'color_temp': %w", err)
		}
	}

	if a.ErrCode != nil {
		object["err_code"], err = json.Marshal(a.ErrCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_code': %w", err)
		}
	}

	if a.Hue != nil {
		object["hue"], err = json.Marshal(a.Hue)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hue': %w", err)
		}
	}

	if a.Mode != nil {
		object["mode"], err = json.Marshal(a.Mode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mode': %w", err)
		}
	}

	if a.OnOff != nil {
		object["on_off"], err = json.Marshal(a.OnOff)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'on_off': %w", err)
		}
	}

	if a.Saturation != nil {
		object["saturation"], err = json.Marshal(a.Saturation)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'saturation': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LightTransitionState. Returns the specified
// element and whether it was found
func (a LightTransitionState) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LightTransitionState
func (a *LightTransitionState) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LightTransitionState to handle AdditionalProperties
func (a *LightTransitionState) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["brightness"]; found {
		err = json.Unmarshal(raw, &a.Brightness)
		if err != nil {
			return fmt.Errorf("error reading 'brightness': %w", err)
		}
		delete(object, "brightness")
	}

	if raw, found := object["color_temp"]; found {
		err = json.Unmarshal(raw, &a.ColorTemp)
		if err != nil {
			return fmt.Errorf("error reading 'color_temp': %w", err)
		}
		delete(object, "color_temp")
	}

	if raw, found := object["hue"]; found {
		err = json.Unmarshal(raw, &a.Hue)
		if err != nil {
			return fmt.Errorf("error reading 'hue': %w", err)
		}
		delete(object, "hue")
	}

	if raw, found := object["on_off"]; found {
		err = json.Unmarshal(raw, &a.OnOff)
		if err != nil {
			return fmt.Errorf("error reading 'on_off': %w", err)
		}
		delete(object, "on_off")
	}

	if raw, found := object["saturation"]; found {
		err = json.Unmarshal(raw, &a.Saturation)
		if err != nil {
			return fmt.Errorf("error reading 'saturation': %w", err)
		}
		delete(object, "saturation")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LightTransitionState to handle AdditionalProperties
func (a LightTransitionState) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Brightness != nil {
		object["brightness"], err = json.Marshal(a.Brightness)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'brightness': %w", err)
		}
	}

	if a.ColorTemp != nil {
		object["color_temp"], err = json.Marshal(a.ColorTemp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'color_temp': %w", err)
		}
	}

	if a.Hue != nil {
		object["hue"], err = json.Marshal(a.Hue)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hue': %w", err)
		}
	}

	if a.OnOff != nil {
		object["on_off"], err = json.Marshal(a.OnOff)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'on_off': %w", err)
		}
	}

	if a.Saturation != nil {
		object["saturation"], err = json.Marshal(a.Saturation)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'saturation': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LightingCommandResult. Returns the specified
// element and whether it was found
func (a LightingCommandResult) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LightingCommandResult
func (a *LightingCommandResult) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LightingCommandResult to handle AdditionalProperties
func (a *LightingCommandResult) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["smartlife.iot.smartbulb.lightingservice"]; found {
		err = json.Unmarshal(raw, &a.SmartlifeIotSmartbulbLightingservice)
		if err != nil {
			return fmt.Errorf("error reading 'smartlife.iot.smartbulb.lightingservice': %w", err)
		}
		delete(object, "smartlife.iot.smartbulb.lightingservice")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LightingCommandResult to handle AdditionalProperties
func (a LightingCommandResult) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.SmartlifeIotSmartbulbLightingservice != nil {
		object["smartlife.iot.smartbulb.lightingservice"], err = json.Marshal(a.SmartlifeIotSmartbulbLightingservice)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'smartlife.iot.smartbulb.lightingservice': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LightingCommandResult_SmartlifeIotSmartbulbLightingservice. Returns the specified
// element and whether it was found
func (a LightingCommandResult_SmartlifeIotSmartbulbLightingservice) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LightingCommandResult_SmartlifeIotSmartbulbLightingservice
func (a *LightingCommandResult_SmartlifeIotSmartbulbLightingservice) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LightingCommandResult_SmartlifeIotSmartbulbLightingservice to handle AdditionalProperties
func (a *LightingCommandResult_SmartlifeIotSmartbulbLightingservice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["get_light_state"]; found {
		err = json.Unmarshal(raw, &a.GetLightState)
		if err != nil {
			return fmt.Errorf("error reading 'get_light_state': %w", err)
		}
		delete(object, "get_light_state")
	}

	if raw, found := object["transition_light_state"]; found {
		err = json.Unmarshal(raw, &a.TransitionLightState)
		if err != nil {
			return fmt.Errorf("error reading 'transition_light_state': %w", err)
		}
		delete(object, "transition_light_state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LightingCommandResult_SmartlifeIotSmartbulbLightingservice to handle AdditionalProperties
func (a LightingCommandResult_SmartlifeIotSmartbulbLightingservice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.GetLightState != nil {
		object["get_light_state"], err = json.Marshal(a.GetLightState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'get_light_state': %w", err)
		}
	}

	if a.TransitionLightState != nil {
		object["transition_light_state"], err = json.Marshal(a.TransitionLightState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'transition_light_state': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SysInfo. Returns the specified
// element and whether it was found
func (a SysInfo) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SysInfo
func (a *SysInfo) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SysInfo to handle AdditionalProperties
func (a *SysInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["alias"]; found {
		err = json.Unmarshal(raw, &a.Alias)
		if err != nil {
			return fmt.Errorf("error reading 'alias': %w", err)
		}
		delete(object, "alias")
	}

	if raw, found := object["deviceId"]; found {
		err = json.Unmarshal(raw, &a.DeviceId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceId': %w", err)
		}
		delete(object, "deviceId")
	}

	if raw, found := object["err_code"]; found {
		err = json.Unmarshal(raw, &a.ErrCode)
		if err != nil {
			return fmt.Errorf("error reading 'err_code': %w", err)
		}
		delete(object, "err_code")
	}

	if raw, found := object["hw_ver"]; found {
		err = json.Unmarshal(raw, &a.HwVer)
		if err != nil {
			return fmt.Errorf("error reading 'hw_ver': %w", err)
		}
		delete(object, "hw_ver")
	}

	if raw, found := object["model"]; found {
		err = json.Unmarshal(raw, &a.Model)
		if err != nil {
			return fmt.Errorf("error reading 'model': %w", err)
		}
		delete(object, "model")
	}

	if raw, found := object["on_time"]; found {
		err = json.Unmarshal(raw, &a.OnTime)
		if err != nil {
			return fmt.Errorf("error reading 'on_time': %w", err)
		}
		delete(object, "on_time")
	}

	if raw, found := object["relay_state"]; found {
		err = json.Unmarshal(raw, &a.RelayState)
		if err != nil {
			return fmt.Errorf("error reading 'relay_state': %w", err)
		}
		delete(object, "relay_state")
	}

	if raw, found := object["sw_ver"]; found {
		err = json.Unmarshal(raw, &a.SwVer)
		if err != nil {
			return fmt.Errorf("error reading 'sw_ver': %w", err)
		}
		delete(object, "sw_ver")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SysInfo to handle AdditionalProperties
func (a SysInfo) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Alias != nil {
		object["alias"], err = json.Marshal(a.Alias)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'alias': %w", err)
		}
	}

	if a.DeviceId != nil {
		object["deviceId"], err = json.Marshal(a.DeviceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceId': %w", err)
		}
	}

	if a.ErrCode != nil {
		object["err_code"], err = json.Marshal(a.ErrCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'err_code': %w", err)
		}
	}

	if a.HwVer != nil {
		object["hw_ver"], err = json.Marshal(a.HwVer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hw_ver': %w", err)
		}
	}

	if a.Model != nil {
		object["model"], err = json.Marshal(a.Model)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'model': %w", err)
		}
	}

	if a.OnTime != nil {
		object["on_time"], err = json.Marshal(a.OnTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'on_time': %w", err)
		}
	}

	if a.RelayState != nil {
		object["relay_state"], err = json.Marshal(a.RelayState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'relay_state': %w", err)
		}
	}

	if a.SwVer != nil {
		object["sw_ver"], err = json.Marshal(a.SwVer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sw_ver': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SystemCommandResult. Returns the specified
// element and whether it was found
func (a SystemCommandResult) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SystemCommandResult
func (a *SystemCommandResult) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SystemCommandResult to handle AdditionalProperties
func (a *SystemCommandResult) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["system"]; found {
		err = json.Unmarshal(raw, &a.System)
		if err != nil {
			return fmt.Errorf("error reading 'system': %w", err)
		}
		delete(object, "system")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SystemCommandResult to handle AdditionalProperties
func (a SystemCommandResult) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.System != nil {
		object["system"], err = json.Marshal(a.System)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'system': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SystemCommandResult_System. Returns the specified
// element and whether it was found
func (a SystemCommandResult_System) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SystemCommandResult_System
func (a *SystemCommandResult_System) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SystemCommandResult_System to handle AdditionalProperties
func (a *SystemCommandResult_System) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["get_sysinfo"]; found {
		err = json.Unmarshal(raw, &a.GetSysinfo)
		if err != nil {
			return fmt.Errorf("error reading 'get_sysinfo': %w", err)
		}
		delete(object, "get_sysinfo")
	}

	if raw, found := object["reboot"]; found {
		err = json.Unmarshal(raw, &a.Reboot)
		if err != nil {
			return fmt.Errorf("error reading 'reboot': %w", err)
		}
		delete(object, "reboot")
	}

	if raw, found := object["set_dev_alias"]; found {
		err = json.Unmarshal(raw, &a.SetDevAlias)
		if err != nil {
			return fmt.Errorf("error reading 'set_dev_alias': %w", err)
		}
		delete(object, "set_dev_alias")
	}

	if raw, found := object["set_relay_state"]; found {
		err = json.Unmarshal(raw, &a.SetRelayState)
		if err != nil {
			return fmt.Errorf("error reading 'set_relay_state': %w", err)
		}
		delete(object, "set_relay_state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SystemCommandResult_System to handle AdditionalProperties
func (a SystemCommandResult_System) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.GetSysinfo != nil {
		object["get_sysinfo"], err = json.Marshal(a.GetSysinfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'get_sysinfo': %w", err)
		}
	}

	if a.Reboot != nil {
		object["reboot"], err = json.Marshal(a.Reboot)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reboot': %w", err)
		}
	}

	if a.SetDevAlias != nil {
		object["set_dev_alias"], err = json.Marshal(a.SetDevAlias)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'set_dev_alias': %w", err)
		}
	}

	if a.SetRelayState != nil {
		object["set_relay_state"], err = json.Marshal(a.SetRelayState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'set_relay_state': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsSystemGetSysInfoCommand returns the union data inside the PassthroughCommand as a SystemGetSysInfoCommand
func (t PassthroughCommand) AsSystemGetSysInfoCommand() (SystemGetSysInfoCommand, error) {
	var body SystemGetSysInfoCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemGetSysInfoCommand overwrites any union data inside the PassthroughCommand as the provided SystemGetSysInfoCommand
func (t *PassthroughCommand) FromSystemGetSysInfoCommand(v SystemGetSysInfoCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemGetSysInfoCommand performs a merge with any union data inside the PassthroughCommand, using the provided SystemGetSysInfoCommand
func (t *PassthroughCommand) MergeSystemGetSysInfoCommand(v SystemGetSysInfoCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSystemSetRelayStateCommand returns the union data inside the PassthroughCommand as a SystemSetRelayStateCommand
func (t PassthroughCommand) AsSystemSetRelayStateCommand() (SystemSetRelayStateCommand, error) {
	var body SystemSetRelayStateCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemSetRelayStateCommand overwrites any union data inside the PassthroughCommand as the provided SystemSetRelayStateCommand
func (t *PassthroughCommand) FromSystemSetRelayStateCommand(v SystemSetRelayStateCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemSetRelayStateCommand performs a merge with any union data inside the PassthroughCommand, using the provided SystemSetRelayStateCommand
func (t *PassthroughCommand) MergeSystemSetRelayStateCommand(v SystemSetRelayStateCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSystemRebootCommand returns the union data inside the PassthroughCommand as a SystemRebootCommand
func (t PassthroughCommand) AsSystemRebootCommand() (SystemRebootCommand, error) {
	var body SystemRebootCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemRebootCommand overwrites any union data inside the PassthroughCommand as the provided SystemRebootCommand
func (t *PassthroughCommand) FromSystemRebootCommand(v SystemRebootCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemRebootCommand performs a merge with any union data inside the PassthroughCommand, using the provided SystemRebootCommand
func (t *PassthroughCommand) MergeSystemRebootCommand(v SystemRebootCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSystemSetDevAliasCommand returns the union data inside the PassthroughCommand as a SystemSetDevAliasCommand
func (t PassthroughCommand) AsSystemSetDevAliasCommand() (SystemSetDevAliasCommand, error) {
	var body SystemSetDevAliasCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemSetDevAliasCommand overwrites any union data inside the PassthroughCommand as the provided SystemSetDevAliasCommand
func (t *PassthroughCommand) FromSystemSetDevAliasCommand(v SystemSetDevAliasCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemSetDevAliasCommand performs a merge with any union data inside the PassthroughCommand, using the provided SystemSetDevAliasCommand
func (t *PassthroughCommand) MergeSystemSetDevAliasCommand(v SystemSetDevAliasCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLightingGetLightStateCommand returns the union data inside the PassthroughCommand as a LightingGetLightStateCommand
func (t PassthroughCommand) AsLightingGetLightStateCommand() (LightingGetLightStateCommand, error) {
	var body LightingGetLightStateCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLightingGetLightStateCommand overwrites any union data inside the PassthroughCommand as the provided LightingGetLightStateCommand
func (t *PassthroughCommand) FromLightingGetLightStateCommand(v LightingGetLightStateCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLightingGetLightStateCommand performs a merge with any union data inside the PassthroughCommand, using the provided LightingGetLightStateCommand
func (t *PassthroughCommand) MergeLightingGetLightStateCommand(v LightingGetLightStateCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLightingTransitionLightStateCommand returns the union data inside the PassthroughCommand as a LightingTransitionLightStateCommand
func (t PassthroughCommand) AsLightingTransitionLightStateCommand() (LightingTransitionLightStateCommand, error) {
	var body LightingTransitionLightStateCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLightingTransitionLightStateCommand overwrites any union data inside the PassthroughCommand as the provided LightingTransitionLightStateCommand
func (t *PassthroughCommand) FromLightingTransitionLightStateCommand(v LightingTransitionLightStateCommand) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLightingTransitionLightStateCommand performs a merge with any union data inside the PassthroughCommand, using the provided LightingTransitionLightStateCommand
func (t *PassthroughCommand) MergeLightingTransitionLightStateCommand(v LightingTransitionLightStateCommand) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PassthroughCommand) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PassthroughCommand) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSystemCommandResult returns the union data inside the PassthroughCommandResult as a SystemCommandResult
func (t PassthroughCommandResult) AsSystemCommandResult() (SystemCommandResult, error) {
	var body SystemCommandResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemCommandResult overwrites any union data inside the PassthroughCommandResult as the provided SystemCommandResult
func (t *PassthroughCommandResult) FromSystemCommandResult(v SystemCommandResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemCommandResult performs a merge with any union data inside the PassthroughCommandResult, using the provided SystemCommandResult
func (t *PassthroughCommandResult) MergeSystemCommandResult(v SystemCommandResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLightingCommandResult returns the union data inside the PassthroughCommandResult as a LightingCommandResult
func (t PassthroughCommandResult) AsLightingCommandResult() (LightingCommandResult, error) {
	var body LightingCommandResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLightingCommandResult overwrites any union data inside the PassthroughCommandResult as the provided LightingCommandResult
func (t *PassthroughCommandResult) FromLightingCommandResult(v LightingCommandResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLightingCommandResult performs a merge with any union data inside the PassthroughCommandResult, using the provided LightingCommandResult
func (t *PassthroughCommandResult) MergeLightingCommandResult(v LightingCommandResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceCommandError returns the union data inside the PassthroughCommandResult as a DeviceCommandError
func (t PassthroughCommandResult) AsDeviceCommandError() (DeviceCommandError, error) {
	var body DeviceCommandError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceCommandError overwrites any union data inside the PassthroughCommandResult as the provided DeviceCommandError
func (t *PassthroughCommandResult) FromDeviceCommandError(v DeviceCommandError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceCommandError performs a merge with any union data inside the PassthroughCommandResult, using the provided DeviceCommandError
func (t *PassthroughCommandResult) MergeDeviceCommandError(v DeviceCommandError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PassthroughCommandResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PassthroughCommandResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
