// Code generated by tools/wireconstants; DO NOT EDIT.

package dependencymodels

// AppType is a schema-derived wire value.
const AppType = "Tapo_Android"

// BaseURLAsiaPacific is a schema-derived wire value.
const BaseURLAsiaPacific = "https://aps1-wap.tplinkcloud.com"

// BaseURLEU is a schema-derived wire value.
const BaseURLEU = "https://eu-wap.tplinkcloud.com"

// BaseURLGlobal is a schema-derived wire value.
const BaseURLGlobal = "https://wap.tplinkcloud.com"

// BaseURLUS is a schema-derived wire value.
const BaseURLUS = "https://use1-wap.tplinkcloud.com"

// CloudErrorCodeAuthentication is a schema-derived wire value.
const CloudErrorCodeAuthentication = -20601

// CloudErrorCodeOK is a schema-derived wire value.
const CloudErrorCodeOK = 0

// CloudErrorCodeParameter is a schema-derived wire value.
const CloudErrorCodeParameter = -20104

// CloudErrorCodeRateLimited is a schema-derived wire value.
const CloudErrorCodeRateLimited = -20004

// CloudErrorCodeTokenExpired is a schema-derived wire value.
const CloudErrorCodeTokenExpired = -20651

// CloudRequestContentType is a schema-derived wire value.
const CloudRequestContentType = "application/json"

// CloudRequestContentTypeHeader is a schema-derived wire value.
const CloudRequestContentTypeHeader = "Content-Type"

// CloudRequestHTTPMethod is a schema-derived wire value.
const CloudRequestHTTPMethod = "POST"

// CloudRequestPath is a schema-derived wire value.
const CloudRequestPath = "/"

// CmdGetLightState is a schema-derived wire value.
const CmdGetLightState = "get_light_state"

// CmdGetSysInfo is a schema-derived wire value.
const CmdGetSysInfo = "get_sysinfo"

// CmdReboot is a schema-derived wire value.
const CmdReboot = "reboot"

// CmdSetDevAlias is a schema-derived wire value.
const CmdSetDevAlias = "set_dev_alias"

// CmdSetRelayState is a schema-derived wire value.
const CmdSetRelayState = "set_relay_state"

// CmdTransitionLightState is a schema-derived wire value.
const CmdTransitionLightState = "transition_light_state"

// DefaultBaseURL is a schema-derived wire value.
const DefaultBaseURL = BaseURLUS

// DeviceCapabilityDisabled is a schema-derived wire value.
const DeviceCapabilityDisabled = 0

// DeviceCapabilityEnabled is a schema-derived wire value.
const DeviceCapabilityEnabled = 1

// DeviceErrorOK is a schema-derived wire value.
const DeviceErrorOK = 0

// DeviceErrorUnsupported is a schema-derived wire value.
const DeviceErrorUnsupported = -1

// DeviceStateOff is a schema-derived wire value.
const DeviceStateOff = 0

// DeviceStateOn is a schema-derived wire value.
const DeviceStateOn = 1

// DeviceTypeRangeExtenderPlug is a schema-derived wire value.
const DeviceTypeRangeExtenderPlug = "IOT.RANGEEXTENDER.SMARTPLUG"

// DeviceTypeSmartBulb is a schema-derived wire value.
const DeviceTypeSmartBulb = "IOT.SMARTBULB"

// DeviceTypeSmartPlug is a schema-derived wire value.
const DeviceTypeSmartPlug = "IOT.SMARTPLUGSWITCH"

// MethodGetDeviceList is a schema-derived wire value.
const MethodGetDeviceList = "getDeviceList"

// MethodLogin is a schema-derived wire value.
const MethodLogin = "login"

// MethodPassthrough is a schema-derived wire value.
const MethodPassthrough = "passthrough"

// NamespaceLightingService is a schema-derived wire value.
const NamespaceLightingService = "smartlife.iot.smartbulb.lightingservice"

// NamespaceSystem is a schema-derived wire value.
const NamespaceSystem = "system"

// TerminalUUID is a schema-derived wire value.
const TerminalUUID = "go-tplink-client"

// TokenQueryKey is a schema-derived wire value.
const TokenQueryKey = "token"
