// Code generated by tools/wireconstants; DO NOT EDIT.

package tplink

import "github.com/portpowered/go-tplink/pkg/dependencymodels"

// AppType is retained for source compatibility.
const AppType = dependencymodels.AppType

// BaseURLAsiaPacific is retained for source compatibility.
const BaseURLAsiaPacific = dependencymodels.BaseURLAsiaPacific

// BaseURLEU is retained for source compatibility.
const BaseURLEU = dependencymodels.BaseURLEU

// BaseURLGlobal is retained for source compatibility.
const BaseURLGlobal = dependencymodels.BaseURLGlobal

// BaseURLUS is retained for source compatibility.
const BaseURLUS = dependencymodels.BaseURLUS

// CmdGetLightState is retained for source compatibility.
const CmdGetLightState = dependencymodels.CmdGetLightState

// CmdGetSysInfo is retained for source compatibility.
const CmdGetSysInfo = dependencymodels.CmdGetSysInfo

// CmdReboot is retained for source compatibility.
const CmdReboot = dependencymodels.CmdReboot

// CmdSetDevAlias is retained for source compatibility.
const CmdSetDevAlias = dependencymodels.CmdSetDevAlias

// CmdSetRelayState is retained for source compatibility.
const CmdSetRelayState = dependencymodels.CmdSetRelayState

// CmdTransitionLightState is retained for source compatibility.
const CmdTransitionLightState = dependencymodels.CmdTransitionLightState

// DefaultBaseURL is retained for source compatibility.
const DefaultBaseURL = dependencymodels.DefaultBaseURL

// MethodGetDeviceList is retained for source compatibility.
const MethodGetDeviceList = dependencymodels.MethodGetDeviceList

// MethodLogin is retained for source compatibility.
const MethodLogin = dependencymodels.MethodLogin

// MethodPassthrough is retained for source compatibility.
const MethodPassthrough = dependencymodels.MethodPassthrough

// NamespaceLightingService is retained for source compatibility.
const NamespaceLightingService = dependencymodels.NamespaceLightingService

// NamespaceSystem is retained for source compatibility.
const NamespaceSystem = dependencymodels.NamespaceSystem
