// Package tplinkmodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tplinkmodels

// Defines values for EndpointType.
const (
	EndpointTypeBulb  EndpointType = "Bulb"
	EndpointTypeOther EndpointType = "Other"
	EndpointTypePlug  EndpointType = "Plug"
)

// Valid indicates whether the value is a known member of the EndpointType enum.
func (e EndpointType) Valid() bool {
	switch e {
	case EndpointTypeBulb:
		return true
	case EndpointTypeOther:
		return true
	case EndpointTypePlug:
		return true
	default:
		return false
	}
}

// AuthContext Authentication supplied for one account request.
type AuthContext struct {
	AccessToken string `json:"AccessToken,omitempty"`
}

// BrightnessResult A bulb's current brightness from 0 through 100.
type BrightnessResult struct {
	Brightness int `json:"Brightness,omitempty"`
}

// Capabilities Capabilities inferred from device metadata.
type Capabilities struct {
	Brightness bool `json:"Brightness,omitempty"`
	Color      bool `json:"Color,omitempty"`
	ColorTemp  bool `json:"ColorTemp,omitempty"`
	OnOff      bool `json:"OnOff,omitempty"`
}

// ColorResult A bulb's current hue and saturation.
type ColorResult struct {
	Hue        int `json:"Hue,omitempty"`
	Saturation int `json:"Saturation,omitempty"`
}

// ColorTempResult A bulb's current color temperature in Kelvin.
type ColorTempResult struct {
	ColorTemp int `json:"ColorTemp,omitempty"`
}

// Device Device metadata exposed to callers by the client.
type Device struct {
	Alias        string `json:"alias,omitempty"`
	AppServerURL string `json:"appServerUrl,omitempty"`
	Brightness   int    `json:"brightness,omitempty"`
	DeviceHwVer  string `json:"deviceHwVer,omitempty"`
	DeviceID     string `json:"deviceId,omitempty"`
	DeviceMac    string `json:"deviceMac,omitempty"`
	DeviceModel  string `json:"deviceModel,omitempty"`
	DeviceRegion string `json:"deviceRegion,omitempty"`

	// DeviceType Unknown device types are retained and classify as Other.
	DeviceType      string `json:"deviceType,omitempty"`
	FwID            string `json:"fwId,omitempty"`
	FwVer           string `json:"fwVer,omitempty"`
	HwID            string `json:"hwId,omitempty"`
	IsSameRegion    bool   `json:"isSameRegion,omitempty"`
	IsColor         int    `json:"is_color,omitempty"`
	IsDimmable      int    `json:"is_dimmable,omitempty"`
	IsVariableColor int    `json:"is_variable_color_temp,omitempty"`
	OemID           string `json:"oemId,omitempty"`
	Status          int    `json:"status,omitempty"`
}

// EndpointType Classification assigned to a device by ClassifyDevice.
type EndpointType string

// GetBrightnessRequest Identifies a bulb whose brightness should be read.
type GetBrightnessRequest struct {
	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`
}

// GetColorRequest Identifies a bulb whose hue and saturation should be read.
type GetColorRequest struct {
	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`
}

// GetColorTempRequest Identifies a bulb whose color temperature should be read.
type GetColorTempRequest struct {
	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`
}

// GetDevicesRequest Identifies the account whose devices should be listed.
type GetDevicesRequest struct {
	// Auth Authentication supplied for one account request.
	Auth AuthContext `json:"Auth,omitempty"`
}

// GetDevicesResult Devices returned by the cloud account.
type GetDevicesResult struct {
	Devices []Device `json:"Devices,omitempty"`
}

// GetLightStateRequest Identifies a bulb whose state should be read.
type GetLightStateRequest struct {
	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`
}

// GetPowerStateRequest Identifies a device whose power state should be read.
type GetPowerStateRequest struct {
	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`
}

// LightState Current state returned by a smart bulb.
type LightState struct {
	Brightness int    `json:"brightness,omitempty"`
	ColorTemp  int    `json:"color_temp,omitempty"`
	ErrCode    int    `json:"err_code,omitempty"`
	Hue        int    `json:"hue,omitempty"`
	Mode       string `json:"mode,omitempty"`
	OnOff      int    `json:"on_off,omitempty"`
	Saturation int    `json:"saturation,omitempty"`
}

// LoginRequest Account credentials used to create a cloud session.
type LoginRequest struct {
	Email    string `json:"Email,omitempty"`
	Password string `json:"Password,omitempty"`
}

// LoginResult Fields returned after successful authentication.
type LoginResult struct {
	AccountID   string `json:"accountId,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	Email       string `json:"email,omitempty"`
	RegTime     string `json:"regTime,omitempty"`

	// Token Opaque session token for subsequent authenticated requests.
	Token string `json:"token,omitempty"`
}

// PowerState Power state projected from a plug's get_sysinfo response.
type PowerState struct {
	IsOn   bool `json:"IsOn,omitempty"`
	OnTime int  `json:"OnTime,omitempty"`
}

// RebootRequest Identifies a device to reboot.
type RebootRequest struct {
	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`
}

// SetAliasRequest Specifies the display name for a device.
type SetAliasRequest struct {
	Alias string `json:"Alias,omitempty"`

	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`
}

// SetBrightnessRequest Specifies a bulb brightness from 0 through 100.
type SetBrightnessRequest struct {
	// Auth Authentication supplied for one account request.
	Auth       AuthContext `json:"Auth,omitempty"`
	Brightness int         `json:"Brightness,omitempty"`
	DeviceID   string      `json:"DeviceID,omitempty"`
}

// SetColorRequest Specifies a bulb hue and saturation.
type SetColorRequest struct {
	// Auth Authentication supplied for one account request.
	Auth       AuthContext `json:"Auth,omitempty"`
	DeviceID   string      `json:"DeviceID,omitempty"`
	Hue        int         `json:"Hue,omitempty"`
	Saturation int         `json:"Saturation,omitempty"`
}

// SetColorTempRequest Specifies a bulb color temperature in Kelvin.
type SetColorTempRequest struct {
	// Auth Authentication supplied for one account request.
	Auth      AuthContext `json:"Auth,omitempty"`
	ColorTemp int         `json:"ColorTemp,omitempty"`
	DeviceID  string      `json:"DeviceID,omitempty"`
}

// SetLightStateRequest Specifies arbitrary transition_light_state parameters.
type SetLightStateRequest struct {
	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`

	// State State fields sent to the device, including fields not listed here.
	State map[string]interface{} `json:"State,omitempty"`
}

// SysInfo Parsed system information returned by a plug.
type SysInfo struct {
	Alias      string `json:"alias,omitempty"`
	DeviceID   string `json:"deviceId,omitempty"`
	ErrCode    int    `json:"err_code,omitempty"`
	HwVer      string `json:"hw_ver,omitempty"`
	Model      string `json:"model,omitempty"`
	OnTime     int    `json:"on_time,omitempty"`
	RelayState int    `json:"relay_state,omitempty"`
	SwVer      string `json:"sw_ver,omitempty"`
}

// TurnOffRequest Identifies a device to turn off.
type TurnOffRequest struct {
	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`
}

// TurnOnRequest Identifies a device to turn on.
type TurnOnRequest struct {
	// Auth Authentication supplied for one account request.
	Auth     AuthContext `json:"Auth,omitempty"`
	DeviceID string      `json:"DeviceID,omitempty"`
}
