// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package main

// AuthStatusOutput defines model for AuthStatusOutput.
type AuthStatusOutput struct {
	Authenticated bool `json:"authenticated"`
}

// DeviceSummary defines model for DeviceSummary.
type DeviceSummary struct {
	Alias      string `json:"alias"`
	DeviceId   string `json:"deviceId"`
	DeviceType string `json:"deviceType"`
	Model      string `json:"model"`
	Status     int    `json:"status"`
}

// LightStateOutput defines model for LightStateOutput.
type LightStateOutput struct {
	Brightness int    `json:"brightness"`
	ColorTemp  int    `json:"colorTemp"`
	Hue        int    `json:"hue"`
	IsOn       bool   `json:"isOn"`
	Mode       string `json:"mode"`
	Saturation int    `json:"saturation"`
}

// LoginCredentials defines model for LoginCredentials.
type LoginCredentials struct {
	Email string `json:"email"`

	// Password Account password. The CLI treats this input as secret.
	Password string `json:"password"`
}

// PowerStateOutput defines model for PowerStateOutput.
type PowerStateOutput struct {
	IsOn   bool `json:"isOn"`
	OnTime int  `json:"onTime"`
}

// StoredCredentials defines model for StoredCredentials.
type StoredCredentials struct {
	// AccessToken Provider token stored locally as a secret.
	AccessToken string `json:"accessToken"`
}
